// Inbox Pro - AI-Powered Email Client
console.log('🚀 Inbox Pro запускається...');

// ==================== CONFIGURATION ====================
const TRANSLATIONS = {
    en: {
        // Loading
        loading: "Loading Inbox Pro...",
        
        // Login Screen
        welcomeBack: "Welcome Back",
        createAccount: "Create Account",
        resetPassword: "Reset Password",
        emailAddress: "Email Address",
        password: "Password",
        fullName: "Full Name",
        confirmPassword: "Confirm Password",
        rememberMe: "Remember me",
        forgotPassword: "Forgot password?",
        signIn: "Sign In",
        newUser: "New user?",
        haveAccount: "Already have an account?",
        rememberPassword: "Remember password?",
        sendResetLink: "Send Reset Link",
        createAccountBtn: "Create Account",
        passwordHint: "Minimum 8 characters with letters & numbers",
        
        // Features
        aiSpamFilter: "AI Spam Filter",
        smartSorting: "Smart Sorting",
        securePrivate: "Secure & Private",
        
        // Main App
        aiActive: "AI Active",
        aiOrganizing: "AI is organizing your inbox. <strong>15</strong> emails sorted automatically.",
        searchPlaceholder: "Search emails, contacts, subjects...",
        compose: "Compose",
        aiCompose: "AI Compose",
        archive: "Archive",
        important: "Important",
        delete: "Delete",
        snooze: "Snooze",
        folders: "FOLDERS",
        inbox: "Inbox",
        starred: "Starred",
        sent: "Sent",
        drafts: "Drafts",
        spam: "Spam",
        trash: "Trash",
        labels: "LABELS",
        work: "Work",
        personal: "Personal",
        travel: "Travel",
        social: "Social",
        emailStats: "Email Stats",
        total: "Total",
        unread: "Unread",
        storage: "Storage",
        used: "used",
        
        // Toolbar
        newestFirst: "Newest first",
        oldestFirst: "Oldest first",
        importantFirst: "Important first",
        unreadFirst: "Unread first",
        selectAll: "Select All",
        markRead: "Mark as Read",
        withAttachments: "With Attachments",
        all: "All",
        
        // Email Viewer
        reply: "Reply",
        forward: "Forward",
        print: "Print",
        back: "Back",
        
        // Compose Modal
        newMessage: "New Message",
        to: "To",
        subject: "Subject",
        writeMessage: "Write your message here...",
        send: "Send",
        saveDraft: "Save Draft",
        importantEmail: "Important",
        aiGenerate: "AI Generate",
        aiWriting: "AI is writing your email...",
        aiPrompt: "Describe what you want to write about:",
        aiGenerateBtn: "Generate Email",
        
        // Settings
        settings: "Settings",
        profile: "Profile",
        appearance: "Appearance",
        notifications: "Notifications",
        language: "Language",
        enableNotifications: "Enable notifications",
        interfaceLanguage: "Interface Language",
        saveChanges: "Save Changes",
        
        // Quick Actions
        quickActions: "Quick Actions",
        markImportant: "Mark as Important",
        markUnread: "Mark as Unread",
        addLabel: "Add Label",
        moveToFolder: "Move to Folder",
        
        // Toast Messages
        loginSuccess: "Login successful! Welcome to Inbox Pro.",
        registerSuccess: "Account created successfully!",
        emailSent: "Email sent successfully!",
        emailSaved: "Draft saved successfully!",
        aiGenerated: "Email generated by AI!",
        themeChanged: "Theme changed to",
        languageChanged: "Language changed to"
    },
    
    ua: {
        loading: "Завантаження Inbox Pro...",
        welcomeBack: "З поверненням",
        createAccount: "Створити акаунт",
        resetPassword: "Скинути пароль",
        emailAddress: "Електронна адреса",
        password: "Пароль",
        fullName: "Повне ім'я",
        confirmPassword: "Підтвердіть пароль",
        rememberMe: "Запам'ятати мене",
        forgotPassword: "Забули пароль?",
        signIn: "Увійти",
        newUser: "Новий користувач?",
        haveAccount: "Вже маєте акаунт?",
        rememberPassword: "Пам'ятаєте пароль?",
        sendResetLink: "Надіслати посилання",
        createAccountBtn: "Створити акаунт",
        passwordHint: "Мінімум 8 символів з літерами та цифрами",
        
        aiSpamFilter: "AI Фільтр Спаму",
        smartSorting: "Розумне Сортування",
        securePrivate: "Захищено & Приватно",
        
        aiActive: "AI Активний",
        aiOrganizing: "AI організовує вашу пошту. <strong>15</strong> листів відсортовано автоматично.",
        searchPlaceholder: "Пошук листів, контактів, тем...",
        compose: "Написати",
        aiCompose: "AI Написати",
        archive: "Архівувати",
        important: "Важливе",
        delete: "Видалити",
        snooze: "Відкласти",
        folders: "ПАПКИ",
        inbox: "Вхідні",
        starred: "Зірочка",
        sent: "Надіслані",
        drafts: "Чернетки",
        spam: "Спам",
        trash: "Кошик",
        labels: "МІТКИ",
        work: "Робота",
        personal: "Особисте",
        travel: "Подорожі",
        social: "Соціальне",
        emailStats: "Статистика",
        total: "Всього",
        unread: "Непрочитані",
        storage: "Сховище",
        used: "використано",
        
        newestFirst: "Спочатку нові",
        oldestFirst: "Спочатку старі",
        importantFirst: "Спочатку важливі",
        unreadFirst: "Спочатку непрочитані",
        selectAll: "Вибрати все",
        markRead: "Позначити прочитаним",
        withAttachments: "З файлами",
        all: "Всі",
        
        reply: "Відповісти",
        forward: "Переслати",
        print: "Друк",
        back: "Назад",
        
        newMessage: "Нове повідомлення",
        to: "Кому",
        subject: "Тема",
        writeMessage: "Напишіть ваше повідомлення тут...",
        send: "Надіслати",
        saveDraft: "Зберегти чернетку",
        importantEmail: "Важливо",
        aiGenerate: "AI Згенерувати",
        aiWriting: "AI пише ваш лист...",
        aiPrompt: "Опишіть, про що хочете написати:",
        aiGenerateBtn: "Згенерувати Лист",
        
        settings: "Налаштування",
        profile: "Профіль",
        appearance: "Зовнішній вигляд",
        notifications: "Сповіщення",
        language: "Мова",
        enableNotifications: "Увімкнути сповіщення",
        interfaceLanguage: "Мова інтерфейсу",
        saveChanges: "Зберегти зміни",
        
        quickActions: "Швидкі дії",
        markImportant: "Позначити важливим",
        markUnread: "Позначити непрочитаним",
        addLabel: "Додати мітку",
        moveToFolder: "Перемістити в папку",
        
        loginSuccess: "Вхід успішний! Ласкаво просимо до Inbox Pro.",
        registerSuccess: "Акаунт успішно створено!",
        emailSent: "Лист успішно відправлено!",
        emailSaved: "Чернетку успішно збережено!",
        aiGenerated: "Лист згенеровано AI!",
        themeChanged: "Тему змінено на",
        languageChanged: "Мову змінено на"
    },
    
    de: {
        loading: "Lade Inbox Pro...",
        welcomeBack: "Willkommen zurück",
        createAccount: "Konto erstellen",
        resetPassword: "Passwort zurücksetzen",
        emailAddress: "E-Mail-Adresse",
        password: "Passwort",
        fullName: "Vollständiger Name",
        confirmPassword: "Passwort bestätigen",
        rememberMe: "Angemeldet bleiben",
        forgotPassword: "Passwort vergessen?",
        signIn: "Anmelden",
        newUser: "Neuer Benutzer?",
        haveAccount: "Bereits ein Konto?",
        rememberPassword: "Passwort erinnern?",
        sendResetLink: "Link senden",
        createAccountBtn: "Konto erstellen",
        passwordHint: "Mindestens 8 Zeichen mit Buchstaben & Zahlen",
        
        aiSpamFilter: "AI Spam-Filter",
        smartSorting: "Intelligente Sortierung",
        securePrivate: "Sicher & Privat",
        
        aiActive: "AI Aktiv",
        aiOrganizing: "AI organisiert Ihren Posteingang. <strong>15</strong> E-Mails automatisch sortiert.",
        searchPlaceholder: "E-Mails, Kontakte, Betreff suchen...",
        compose: "Verfassen",
        aiCompose: "AI Verfassen",
        archive: "Archivieren",
        important: "Wichtig",
        delete: "Löschen",
        snooze: "Stumm",
        folders: "ORDNER",
        inbox: "Posteingang",
        starred: "Favoriten",
        sent: "Gesendet",
        drafts: "Entwürfe",
        spam: "Spam",
        trash: "Papierkorb",
        labels: "ETIKETTEN",
        work: "Arbeit",
        personal: "Privat",
        travel: "Reisen",
        social: "Sozial",
        emailStats: "E-Mail-Statistik",
        total: "Gesamt",
        unread: "Ungelesen",
        storage: "Speicher",
        used: "verwendet",
        
        newestFirst: "Neueste zuerst",
        oldestFirst: "Älteste zuerst",
        importantFirst: "Wichtige zuerst",
        unreadFirst: "Ungelesene zuerst",
        selectAll: "Alle auswählen",
        markRead: "Als gelesen markieren",
        withAttachments: "Mit Anhängen",
        all: "Alle",
        
        reply: "Antworten",
        forward: "Weiterleiten",
        print: "Drucken",
        back: "Zurück",
        
        newMessage: "Neue Nachricht",
        to: "An",
        subject: "Betreff",
        writeMessage: "Schreiben Sie hier Ihre Nachricht...",
        send: "Senden",
        saveDraft: "Entwurf speichern",
        importantEmail: "Wichtig",
        aiGenerate: "AI Generieren",
        aiWriting: "AI schreibt Ihre E-Mail...",
        aiPrompt: "Beschreiben Sie, worüber Sie schreiben möchten:",
        aiGenerateBtn: "E-Mail generieren",
        
        settings: "Einstellungen",
        profile: "Profil",
        appearance: "Erscheinungsbild",
        notifications: "Benachrichtigungen",
        language: "Sprache",
        enableNotifications: "Benachrichtigungen aktivieren",
        interfaceLanguage: "Oberflächensprache",
        saveChanges: "Änderungen speichern",
        
        quickActions: "Schnellaktionen",
        markImportant: "Als wichtig markieren",
        markUnread: "Als ungelesen markieren",
        addLabel: "Etikett hinzufügen",
        moveToFolder: "In Ordner verschieben",
        
        loginSuccess: "Anmeldung erfolgreich! Willkommen bei Inbox Pro.",
        registerSuccess: "Konto erfolgreich erstellt!",
        emailSent: "E-Mail erfolgreich gesendet!",
        emailSaved: "Entwurf erfolgreich gespeichert!",
        aiGenerated: "E-Mail von AI generiert!",
        themeChanged: "Theme geändert zu",
        languageChanged: "Sprache geändert zu"
    },
    
    ru: {
        loading: "Загрузка Inbox Pro...",
        welcomeBack: "С возвращением",
        createAccount: "Создать аккаунт",
        resetPassword: "Сбросить пароль",
        emailAddress: "Адрес электронной почты",
        password: "Пароль",
        fullName: "Полное имя",
        confirmPassword: "Подтвердите пароль",
        rememberMe: "Запомнить меня",
        forgotPassword: "Забыли пароль?",
        signIn: "Войти",
        newUser: "Новый пользователь?",
        haveAccount: "Уже есть аккаунт?",
        rememberPassword: "Помните пароль?",
        sendResetLink: "Отправить ссылку",
        createAccountBtn: "Создать аккаунт",
        passwordHint: "Минимум 8 символов с буквами и цифрами",
        
        aiSpamFilter: "AI Фильтр Спама",
        smartSorting: "Умная Сортировка",
        securePrivate: "Защищено & Приватно",
        
        aiActive: "AI Активен",
        aiOrganizing: "AI организует вашу почту. <strong>15</strong> писем отсортировано автоматически.",
        searchPlaceholder: "Поиск писем, контактов, тем...",
        compose: "Написать",
        aiCompose: "AI Написать",
        archive: "В архив",
        important: "Важное",
        delete: "Удалить",
        snooze: "Отложить",
        folders: "ПАПКИ",
        inbox: "Входящие",
        starred: "Избранное",
        sent: "Отправленные",
        drafts: "Черновики",
        spam: "Спам",
        trash: "Корзина",
        labels: "МЕТКИ",
        work: "Работа",
        personal: "Личное",
        travel: "Путешествия",
        social: "Социальное",
        emailStats: "Статистика",
        total: "Всего",
        unread: "Непрочитанные",
        storage: "Хранилище",
        used: "использовано",
        
        newestFirst: "Сначала новые",
        oldestFirst: "Сначала старые",
        importantFirst: "Сначала важные",
        unreadFirst: "Сначала непрочитанные",
        selectAll: "Выбрать все",
        markRead: "Отметить прочитанным",
        withAttachments: "С файлами",
        all: "Все",
        
        reply: "Ответить",
        forward: "Переслать",
        print: "Печать",
        back: "Назад",
        
        newMessage: "Новое сообщение",
        to: "Кому",
        subject: "Тема",
        writeMessage: "Напишите ваше сообщение здесь...",
        send: "Отправить",
        saveDraft: "Сохранить черновик",
        importantEmail: "Важно",
        aiGenerate: "AI Сгенерировать",
        aiWriting: "AI пишет ваше письмо...",
        aiPrompt: "Опишите, о чем хотите написать:",
        aiGenerateBtn: "Сгенерировать Письмо",
        
        settings: "Настройки",
        profile: "Профиль",
        appearance: "Внешний вид",
        notifications: "Уведомления",
        language: "Язык",
        enableNotifications: "Включить уведомления",
        interfaceLanguage: "Язык интерфейса",
        saveChanges: "Сохранить изменения",
        
        quickActions: "Быстрые действия",
        markImportant: "Отметить важным",
        markUnread: "Отметить непрочитанным",
        addLabel: "Добавить метку",
        moveToFolder: "Переместить в папку",
        
        loginSuccess: "Вход успешный! Добро пожаловать в Inbox Pro.",
        registerSuccess: "Аккаунт успешно создан!",
        emailSent: "Письмо успешно отправлено!",
        emailSaved: "Черновик успешно сохранен!",
        aiGenerated: "Письмо сгенерировано AI!",
        themeChanged: "Тему изменено на",
        languageChanged: "Язык изменен на"
    }
};

// Mock authentication
const mockAuth = {
    onAuthStateChanged: (callback) => {
        setTimeout(() => callback(null), 1000);
    },
    
    login: async (email, password) => {
        await new Promise(resolve => setTimeout(resolve, 1000));
        return { uid: 'mock-user', email, displayName: 'Test User' };
    },
    
    register: async (email, password, name) => {
        await new Promise(resolve => setTimeout(resolve, 1000));
        return { uid: 'mock-user', email, displayName: name };
    },
    
    logout: async () => {
        await new Promise(resolve => setTimeout(resolve, 500));
    },
    
    resetPassword: async (email) => {
        await new Promise(resolve => setTimeout(resolve, 1000));
    }
};

// State
let currentLanguage = 'en';
let currentTheme = 'dark';
let currentUser = null;

// ==================== CORE FUNCTIONS ====================

function hideLoadingScreen() {
    const loadingOverlay = document.getElementById('initialLoading');
    if (loadingOverlay) {
        loadingOverlay.style.opacity = '0';
        loadingOverlay.style.transition = 'opacity 0.5s cubic-bezier(0.4, 0, 0.2, 1)';
        setTimeout(() => {
            loadingOverlay.style.display = 'none';
        }, 500);
    }
}

function showToast(message, type = 'info') {
    const toastContainer = document.getElementById('toastContainer');
    if (!toastContainer) return;
    
    const toast = document.createElement('div');
    toast.className = `toast ${type}`;
    toast.style.animation = 'toastSlideIn 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
    
    const icons = {
        success: '✅',
        error: '❌',
        warning: '⚠️',
        info: 'ℹ️'
    };
    
    toast.innerHTML = `
        <span class="toast-icon">${icons[type] || 'ℹ️'}</span>
        <div class="toast-content">
            <div class="toast-message">${message}</div>
        </div>
        <button class="toast-close">✕</button>
    `;
    
    toastContainer.appendChild(toast);
    
    toast.querySelector('.toast-close').addEventListener('click', () => {
        toast.style.animation = 'toastSlideOut 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
        setTimeout(() => toast.remove(), 300);
    });
    
    setTimeout(() => {
        if (toast.parentNode) {
            toast.style.animation = 'toastSlideOut 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
            setTimeout(() => toast.remove(), 300);
        }
    }, 5000);
}

// ==================== ANIMATION FUNCTIONS ====================

function animateElement(element, animationName, duration = 300) {
    return new Promise(resolve => {
        element.style.animation = `${animationName} ${duration}ms cubic-bezier(0.4, 0, 0.2, 1)`;
        setTimeout(() => {
            element.style.animation = '';
            resolve();
        }, duration);
    });
}

function pulseAnimation(element) {
    element.style.transform = 'scale(1)';
    element.style.transition = 'transform 0.2s cubic-bezier(0.4, 0, 0.2, 1)';
    
    setTimeout(() => {
        element.style.transform = 'scale(1.05)';
    }, 10);
    
    setTimeout(() => {
        element.style.transform = 'scale(1)';
    }, 200);
}

function slideIn(element, direction = 'right') {
    const directions = {
        right: 'translateX(30px)',
        left: 'translateX(-30px)',
        up: 'translateY(30px)',
        down: 'translateY(-30px)'
    };
    
    element.style.opacity = '0';
    element.style.transform = directions[direction] || directions.right;
    element.style.transition = 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
    
    setTimeout(() => {
        element.style.opacity = '1';
        element.style.transform = 'translate(0, 0)';
    }, 10);
}

// ==================== THEME SYSTEM ====================

function setTheme(theme) {
    const oldTheme = currentTheme;
    currentTheme = theme;
    localStorage.setItem('inboxpro-theme', theme);
    
    // Smooth theme transition
    document.body.style.transition = 'background-color 0.5s cubic-bezier(0.4, 0, 0.2, 1), color 0.5s cubic-bezier(0.4, 0, 0.2, 1)';
    document.body.className = theme + '-theme';
    
    // Update theme icon with animation
    const themeIcon = document.querySelector('.theme-icon');
    if (themeIcon) {
        themeIcon.style.transform = 'rotate(180deg) scale(0.8)';
        themeIcon.style.transition = 'transform 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
        
        setTimeout(() => {
            themeIcon.textContent = theme === 'light' ? '☀️' : theme === 'dark' ? '🌙' : '●';
            themeIcon.style.transform = 'rotate(0deg) scale(1)';
        }, 150);
    }
    
    // Update theme buttons
    document.querySelectorAll('.theme-option, .theme-btn').forEach(btn => {
        btn.classList.remove('active');
        if (btn.dataset.theme === theme) {
            btn.classList.add('active');
            pulseAnimation(btn);
        }
    });
    
    // Show toast
    const lang = TRANSLATIONS[currentLanguage];
    showToast(`${lang.themeChanged} ${theme}`, 'success');
    
    // Reset transition
    setTimeout(() => {
        document.body.style.transition = '';
    }, 500);
}

// ==================== LANGUAGE SYSTEM ====================

function setLanguage(lang) {
    if (!TRANSLATIONS[lang]) lang = 'en';
    
    currentLanguage = lang;
    localStorage.setItem('inboxpro-language', lang);
    
    // Update language selectors
    document.querySelectorAll('#languageSelect, #appLanguageSelect, #settingsLanguage').forEach(select => {
        if (select) select.value = lang;
    });
    
    // Update all text elements
    updateTextElements();
    
    // Show toast
    const langNames = { en: 'English', ua: 'Українська', de: 'Deutsch', ru: 'Русский' };
    showToast(`${TRANSLATIONS[lang].languageChanged} ${langNames[lang]}`, 'success');
}

function updateTextElements() {
    const lang = TRANSLATIONS[currentLanguage];
    
    // Helper function to update text
    function updateText(selector, text) {
        const element = document.querySelector(selector);
        if (element) element.textContent = text;
    }
    
    function updatePlaceholder(selector, text) {
        const element = document.querySelector(selector);
        if (element) element.placeholder = text;
    }
    
    // Loading
    updateText('#loadingText', lang.loading);
    
    // Login Form
    updateText('#loginForm h2', `🔑 ${lang.welcomeBack}`);
    updateText('#registerForm h2', `👤 ${lang.createAccount}`);
    updateText('#resetForm h2', `🔑 ${lang.resetPassword}`);
    
    updateText('label[for="loginEmail"]', lang.emailAddress);
    updateText('label[for="loginPassword"]', lang.password);
    updateText('label[for="registerName"]', lang.fullName);
    updateText('label[for="registerEmail"]', lang.emailAddress);
    updateText('label[for="registerPassword"]', lang.password);
    updateText('label[for="registerConfirm"]', lang.confirmPassword);
    updateText('label[for="resetEmail"]', lang.emailAddress);
    
    updatePlaceholder('#loginEmail', 'your@email.com');
    updatePlaceholder('#loginPassword', '••••••••');
    updatePlaceholder('#registerName', lang.fullName);
    updatePlaceholder('#registerEmail', 'your@email.com');
    updatePlaceholder('#registerPassword', '••••••••');
    updatePlaceholder('#registerConfirm', '••••••••');
    updatePlaceholder('#resetEmail', 'your@email.com');
    
    updateText('#rememberMeText', lang.rememberMe);
    updateText('#newUserText', lang.newUser);
    updateText('#haveAccountText', lang.haveAccount);
    updateText('#rememberPasswordText', lang.rememberPassword);
    
    updateText('#loginBtn .btn-text', lang.signIn);
    updateText('#registerBtn .btn-text', lang.createAccountBtn);
    updateText('#sendResetBtn .btn-text', lang.sendResetLink);
    
    updateText('.password-hint', lang.passwordHint);
    
    // Features
    const features = document.querySelectorAll('.feature-text');
    if (features.length >= 3) {
        features[0].textContent = lang.aiSpamFilter;
        features[1].textContent = lang.smartSorting;
        features[2].textContent = lang.securePrivate;
    }
    
    // Main App
    updateText('.ai-text', lang.aiActive);
    updateText('.compose-text', lang.compose);
    updateText('.ai-compose-text', lang.aiCompose);
    
    const quickLabels = document.querySelectorAll('.quick-label');
    if (quickLabels.length >= 4) {
        quickLabels[0].textContent = lang.archive;
        quickLabels[1].textContent = lang.important;
        quickLabels[2].textContent = lang.delete;
        quickLabels[3].textContent = lang.snooze;
    }
    
    updateText('.nav-title:first-child', lang.folders);
    updateText('[data-folder="inbox"] .nav-text', lang.inbox);
    updateText('[data-folder="starred"] .nav-text', lang.starred);
    updateText('[data-folder="sent"] .nav-text', lang.sent);
    updateText('[data-folder="drafts"] .nav-text', lang.drafts);
    updateText('[data-folder="spam"] .nav-text', lang.spam);
    updateText('[data-folder="trash"] .nav-text', lang.trash);
    
    updateText('.nav-title:nth-child(3)', lang.labels);
    updateText('[data-label="work"] .label-text', lang.work);
    updateText('[data-label="personal"] .label-text', lang.personal);
    updateText('[data-label="travel"] .label-text', lang.travel);
    updateText('[data-label="social"] .label-text', lang.social);
    
    updateText('.stat-title', lang.emailStats);
    updateText('.stat-label:nth-child(1)', lang.total);
    updateText('.stat-label:nth-child(2)', lang.unread);
    updateText('.stat-label:nth-child(3)', lang.important);
    
    updateText('.storage-title', lang.storage);
    updateText('.storage-info', `4.2GB / 10GB ${lang.used}`);
    
    // Search
    updatePlaceholder('#searchInput', lang.searchPlaceholder);
    
    // Sort options
    const sortSelect = document.getElementById('sortSelect');
    if (sortSelect && sortSelect.children.length >= 4) {
        sortSelect.children[0].textContent = lang.newestFirst;
        sortSelect.children[1].textContent = lang.oldestFirst;
        sortSelect.children[2].textContent = lang.importantFirst;
        sortSelect.children[3].textContent = lang.unreadFirst;
    }
    
    // Filter tags
    const filterTags = document.querySelectorAll('.filter-tag');
    if (filterTags.length >= 4) {
        filterTags[0].querySelector('span:first-child').textContent = lang.all;
        filterTags[1].querySelector('span:first-child').textContent = `${lang.unread}`;
        filterTags[2].querySelector('span:first-child').textContent = `★ ${lang.starred}`;
        filterTags[3].querySelector('span:first-child').textContent = `📎 ${lang.withAttachments}`;
    }
    
    // AI Message
    const aiMessage = document.querySelector('.ai-message');
    if (aiMessage) {
        aiMessage.innerHTML = lang.aiOrganizing;
    }
}

// ==================== AI EMAIL WRITER ====================

async function generateAIEmail(prompt) {
    // Mock AI generation with realistic email examples
    const examples = {
        business: {
            subject: "Meeting Follow-up & Action Items",
            body: `Dear Team,

Following up on our meeting earlier today, here are the key action items:

1. Complete the Q3 reports by Friday
2. Schedule client demo for next week
3. Update project documentation

Let me know if you have any questions.

Best regards,
[Your Name]`
        },
        casual: {
            subject: "Quick update",
            body: `Hey there!

Just wanted to share a quick update about the project. Everything is progressing well and we're on track for the deadline.

Let me know if you need anything from my end.

Cheers!`
        },
        formal: {
            subject: "Formal Inquiry Regarding Your Services",
            body: `To Whom It May Concern,

I am writing to inquire about your services. Could you please provide more information regarding:

1. Pricing structure
2. Service availability
3. Implementation timeline

Thank you for your attention to this matter.

Sincerely,
[Your Name]`
        }
    };
    
    // Simple keyword matching
    let emailType = 'business';
    if (prompt.toLowerCase().includes('casual') || prompt.toLowerCase().includes('friendly')) {
        emailType = 'casual';
    } else if (prompt.toLowerCase().includes('formal') || prompt.toLowerCase().includes('official')) {
        emailType = 'formal';
    }
    
    // Simulate AI thinking delay
    await new Promise(resolve => setTimeout(resolve, 1500));
    
    return examples[emailType];
}

// ==================== QUICK ACTIONS SYSTEM ====================

function setupQuickActions() {
    const emailItems = document.querySelectorAll('.email-item');
    
    emailItems.forEach(item => {
        // Add hover effects
        item.addEventListener('mouseenter', () => {
            item.style.transform = 'translateX(8px)';
            item.style.transition = 'transform 0.2s cubic-bezier(0.4, 0, 0.2, 1)';
        });
        
        item.addEventListener('mouseleave', () => {
            item.style.transform = 'translateX(0)';
        });
        
        // Add context menu
        item.addEventListener('contextmenu', (e) => {
            e.preventDefault();
            showQuickActionsMenu(e, item);
        });
    });
    
    // Keyboard shortcuts
    document.addEventListener('keydown', (e) => {
        // Ctrl/Cmd + S to star
        if ((e.ctrlKey || e.metaKey) && e.key === 's') {
            e.preventDefault();
            const selected = document.querySelector('.email-item:hover');
            if (selected) {
                const starBtn = selected.querySelector('.star-btn');
                if (starBtn) {
                    starBtn.click();
                    showToast('Email starred', 'success');
                }
            }
        }
        
        // Ctrl/Cmd + D to delete
        if ((e.ctrlKey || e.metaKey) && e.key === 'd') {
            e.preventDefault();
            const selected = document.querySelector('.email-item:hover');
            if (selected) {
                selected.style.animation = 'slideOutRight 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
                setTimeout(() => {
                    selected.remove();
                    showToast('Email deleted', 'success');
                }, 300);
            }
        }
        
        // Ctrl/Cmd + A to archive
        if ((e.ctrlKey || e.metaKey) && e.key === 'a') {
            e.preventDefault();
            const selected = document.querySelector('.email-item:hover');
            if (selected) {
                selected.style.animation = 'slideOutLeft 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
                setTimeout(() => {
                    selected.remove();
                    showToast('Email archived', 'success');
                }, 300);
            }
        }
    });
}

function showQuickActionsMenu(e, emailItem) {
    // Remove existing menu
    const existingMenu = document.querySelector('.quick-actions-menu');
    if (existingMenu) existingMenu.remove();
    
    const lang = TRANSLATIONS[currentLanguage];
    
    const menu = document.createElement('div');
    menu.className = 'quick-actions-menu';
    menu.style.left = e.pageX + 'px';
    menu.style.top = e.pageY + 'px';
    menu.style.animation = 'scaleIn 0.2s cubic-bezier(0.4, 0, 0.2, 1)';
    
    menu.innerHTML = `
        <div class="quick-actions-header">
            <span>${lang.quickActions}</span>
        </div>
        <button class="quick-action-item" data-action="star">
            <span class="action-icon">★</span>
            <span>${lang.markImportant}</span>
        </button>
        <button class="quick-action-item" data-action="unread">
            <span class="action-icon">📨</span>
            <span>${lang.markUnread}</span>
        </button>
        <button class="quick-action-item" data-action="label">
            <span class="action-icon">🏷️</span>
            <span>${lang.addLabel}</span>
        </button>
        <button class="quick-action-item" data-action="move">
            <span class="action-icon">📁</span>
            <span>${lang.moveToFolder}</span>
        </button>
    `;
    
    document.body.appendChild(menu);
    
    // Handle menu actions
    menu.querySelectorAll('.quick-action-item').forEach(button => {
        button.addEventListener('click', () => {
            const action = button.dataset.action;
            handleQuickAction(action, emailItem);
            menu.remove();
        });
    });
    
    // Close menu when clicking outside
    setTimeout(() => {
        const closeMenu = (clickEvent) => {
            if (!menu.contains(clickEvent.target)) {
                menu.style.animation = 'scaleOut 0.2s cubic-bezier(0.4, 0, 0.2, 1)';
                setTimeout(() => menu.remove(), 200);
                document.removeEventListener('click', closeMenu);
            }
        };
        document.addEventListener('click', closeMenu);
    }, 100);
}

function handleQuickAction(action, emailItem) {
    const lang = TRANSLATIONS[currentLanguage];
    
    switch(action) {
        case 'star':
            const starBtn = emailItem.querySelector('.star-btn');
            if (starBtn) {
                starBtn.classList.toggle('active');
                starBtn.textContent = starBtn.classList.contains('active') ? '★' : '☆';
                pulseAnimation(starBtn);
                showToast('Email starred', 'success');
            }
            break;
            
        case 'unread':
            emailItem.classList.toggle('unread');
            showToast('Email marked as unread', 'success');
            break;
            
        case 'label':
            showToast('Label added', 'info');
            break;
            
        case 'move':
            showToast('Email moved', 'info');
            break;
    }
}

// ==================== EVENT HANDLERS ====================

function setupAuthForms() {
    // Form switching
    const showRegisterBtn = document.getElementById('showRegister');
    const showLoginBtn = document.getElementById('showLogin');
    const showLoginFromResetBtn = document.getElementById('showLoginFromReset');
    const forgotPasswordBtn = document.getElementById('forgotPasswordBtn');
    
    const loginForm = document.getElementById('loginForm');
    const registerForm = document.getElementById('registerForm');
    const resetForm = document.getElementById('resetForm');
    
    // Switch forms with animation
    [showRegisterBtn, showLoginBtn, forgotPasswordBtn, showLoginFromResetBtn].forEach((btn, index) => {
        if (!btn) return;
        
        btn.addEventListener('click', (e) => {
            e.preventDefault();
            
            // Hide all forms
            [loginForm, registerForm, resetForm].forEach(form => {
                if (form) {
                    form.style.opacity = '0';
                    form.style.transform = 'translateY(10px)';
                    form.style.transition = 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
                    setTimeout(() => {
                        form.classList.remove('active');
                    }, 150);
                }
            });
            
            // Show target form with animation
            setTimeout(() => {
                let targetForm;
                if (btn === showRegisterBtn) targetForm = registerForm;
                else if (btn === showLoginBtn || btn === showLoginFromResetBtn) targetForm = loginForm;
                else if (btn === forgotPasswordBtn) targetForm = resetForm;
                
                if (targetForm) {
                    targetForm.classList.add('active');
                    setTimeout(() => {
                        targetForm.style.opacity = '1';
                        targetForm.style.transform = 'translateY(0)';
                    }, 10);
                }
            }, 150);
        });
    });
    
    // Login button
    const loginBtn = document.getElementById('loginBtn');
    if (loginBtn) {
        loginBtn.addEventListener('click', async () => {
            const email = document.getElementById('loginEmail')?.value.trim();
            const password = document.getElementById('loginPassword')?.value;
            
            if (!email || !password) {
                showToast('Please fill in all fields', 'error');
                return;
            }
            
            try {
                loginBtn.disabled = true;
                loginBtn.innerHTML = '<span class="btn-text">Signing in...</span><span class="btn-icon">⏳</span>';
                loginBtn.style.transform = 'scale(0.98)';
                
                const user = await mockAuth.login(email, password);
                
                // Success animation
                loginBtn.style.transform = 'scale(1)';
                loginBtn.style.background = 'linear-gradient(135deg, #10b981, #059669)';
                
                const lang = TRANSLATIONS[currentLanguage];
                showToast(lang.loginSuccess, 'success');
                
                // Show main app with delay
                setTimeout(() => showMainApp(user), 1000);
                
            } catch (error) {
                showToast('Login failed. Please try again.', 'error');
                loginBtn.disabled = false;
                const lang = TRANSLATIONS[currentLanguage];
                loginBtn.innerHTML = `<span class="btn-text">${lang.signIn}</span><span class="btn-icon">→</span>`;
                loginBtn.style.transform = 'scale(1)';
                loginBtn.style.background = '';
            }
        });
    }
    
    // Register button
    const registerBtn = document.getElementById('registerBtn');
    if (registerBtn) {
        registerBtn.addEventListener('click', async () => {
            const name = document.getElementById('registerName')?.value.trim();
            const email = document.getElementById('registerEmail')?.value.trim();
            const password = document.getElementById('registerPassword')?.value;
            const confirm = document.getElementById('registerConfirm')?.value;
            
            if (!name || !email || !password || !confirm) {
                showToast('Please fill in all fields', 'error');
                return;
            }
            
            if (password !== confirm) {
                showToast('Passwords do not match', 'error');
                return;
            }
            
            if (password.length < 8) {
                showToast('Password must be at least 8 characters', 'error');
                return;
            }
            
            try {
                registerBtn.disabled = true;
                registerBtn.innerHTML = '<span class="btn-text">Creating account...</span><span class="btn-icon">⏳</span>';
                registerBtn.style.transform = 'scale(0.98)';
                
                const user = await mockAuth.register(email, password, name);
                
                // Success animation
                registerBtn.style.transform = 'scale(1)';
                registerBtn.style.background = 'linear-gradient(135deg, #10b981, #059669)';
                
                const lang = TRANSLATIONS[currentLanguage];
                showToast(lang.registerSuccess, 'success');
                
                // Show main app with delay
                setTimeout(() => showMainApp(user), 1000);
                
            } catch (error) {
                showToast('Registration failed. Please try again.', 'error');
                registerBtn.disabled = false;
                const lang = TRANSLATIONS[currentLanguage];
                registerBtn.innerHTML = `<span class="btn-text">${lang.createAccountBtn}</span><span class="btn-icon">✓</span>`;
                registerBtn.style.transform = 'scale(1)';
                registerBtn.style.background = '';
            }
        });
    }
    
    // Password strength indicator
    const passwordInput = document.getElementById('registerPassword');
    if (passwordInput) {
        passwordInput.addEventListener('input', updatePasswordStrength);
    }
}

function updatePasswordStrength() {
    const password = document.getElementById('registerPassword')?.value || '';
    const strengthMeter = document.querySelector('.password-strength-meter');
    if (!strengthMeter) return;
    
    let strength = 0;
    if (password.length >= 8) strength++;
    if (/[A-Z]/.test(password)) strength++;
    if (/[0-9]/.test(password)) strength++;
    if (/[^A-Za-z0-9]/.test(password)) strength++;
    
    strengthMeter.className = 'password-strength-meter';
    strengthMeter.style.transition = 'width 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
    
    if (password.length === 0) {
        strengthMeter.style.width = '0';
    } else if (strength <= 1) {
        strengthMeter.classList.add('weak');
        strengthMeter.style.width = '33%';
    } else if (strength <= 2) {
        strengthMeter.classList.add('medium');
        strengthMeter.style.width = '66%';
    } else {
        strengthMeter.classList.add('strong');
        strengthMeter.style.width = '100%';
    }
}

// ==================== MAIN APP FUNCTIONS ====================

function showMainApp(user) {
    const loginScreen = document.getElementById('loginScreen');
    const app = document.getElementById('app');
    
    // Animate login screen out
    if (loginScreen) {
        loginScreen.style.opacity = '0';
        loginScreen.style.transform = 'translateY(-20px)';
        loginScreen.style.transition = 'all 0.5s cubic-bezier(0.4, 0, 0.2, 1)';
        
        setTimeout(() => {
            loginScreen.style.display = 'none';
        }, 500);
    }
    
    // Animate app in
    if (app) {
        app.style.display = 'flex';
        app.style.opacity = '0';
        app.style.transform = 'translateY(20px)';
        
        setTimeout(() => {
            app.style.opacity = '1';
            app.style.transform = 'translateY(0)';
            app.style.transition = 'all 0.5s cubic-bezier(0.4, 0, 0.2, 1)';
        }, 100);
    }
    
    // Update user info with animation
    updateUserInfo(user);
    
    // Setup quick actions
    setTimeout(setupQuickActions, 500);
}

function updateUserInfo(user) {
    const userNameElement = document.getElementById('userName');
    const userEmailElement = document.getElementById('userEmail');
    const userAvatarElement = document.getElementById('userAvatar');
    
    if (userNameElement) {
        userNameElement.textContent = user.displayName || 'User';
        slideIn(userNameElement, 'right');
    }
    
    if (userEmailElement) {
        userEmailElement.textContent = user.email || '';
        slideIn(userEmailElement, 'right');
    }
    
    if (userAvatarElement) {
        const initials = getInitialsFromName(user.displayName || user.email || 'User');
        userAvatarElement.textContent = initials;
        pulseAnimation(userAvatarElement);
    }
}

function getInitialsFromName(name) {
    const parts = name.split(' ');
    if (parts.length >= 2) {
        return (parts[0].charAt(0) + parts[1].charAt(0)).toUpperCase();
    }
    return name.substring(0, 2).toUpperCase();
}

// ==================== COMPOSE & AI FUNCTIONS ====================

function setupCompose() {
    const composeBtn = document.getElementById('composeBtn');
    const aiComposeBtn = document.getElementById('aiComposeBtn');
    const composeModal = document.getElementById('composeModal');
    const aiComposeModal = document.getElementById('aiComposeModal');
    const closeCompose = document.getElementById('closeCompose');
    const closeAICompose = document.getElementById('closeAICompose');
    const sendMailBtn = document.getElementById('sendMail');
    const saveDraftBtn = document.getElementById('saveDraftBtn');
    const aiGenerateBtn = document.getElementById('aiGenerateBtn');
    const useAIGeneratedBtn = document.getElementById('useAIGeneratedBtn');
    
    // Regular compose
    if (composeBtn && composeModal) {
        composeBtn.addEventListener('click', () => {
            composeModal.classList.remove('hidden');
            document.getElementById('mailTo')?.focus();
            slideIn(composeModal, 'up');
        });
    }
    
    // AI compose
    if (aiComposeBtn && aiComposeModal) {
        aiComposeBtn.addEventListener('click', () => {
            aiComposeModal.classList.remove('hidden');
            document.getElementById('aiPrompt')?.focus();
            slideIn(aiComposeModal, 'up');
        });
    }
    
    // Close buttons
    if (closeCompose && composeModal) {
        closeCompose.addEventListener('click', () => {
            composeModal.style.animation = 'slideOutDown 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
            setTimeout(() => {
                composeModal.classList.add('hidden');
                composeModal.style.animation = '';
                clearComposeForm();
            }, 300);
        });
    }
    
    if (closeAICompose && aiComposeModal) {
        closeAICompose.addEventListener('click', () => {
            aiComposeModal.style.animation = 'slideOutDown 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
            setTimeout(() => {
                aiComposeModal.classList.add('hidden');
                aiComposeModal.style.animation = '';
            }, 300);
        });
    }
    
    // Send email
    if (sendMailBtn) {
        sendMailBtn.addEventListener('click', async () => {
            const to = document.getElementById('mailTo')?.value.trim() || '';
            const subject = document.getElementById('mailSubject')?.value.trim() || '';
            const text = document.getElementById('mailText')?.value.trim() || '';
            
            if (!to || !subject || !text) {
                showToast('Please fill in all fields', 'error');
                return;
            }
            
            // Button animation
            sendMailBtn.disabled = true;
            sendMailBtn.innerHTML = '<span>Sending...</span>';
            sendMailBtn.style.transform = 'scale(0.98)';
            
            // Simulate sending
            await new Promise(resolve => setTimeout(resolve, 1500));
            
            const lang = TRANSLATIONS[currentLanguage];
            showToast(lang.emailSent, 'success');
            
            // Reset button
            setTimeout(() => {
                sendMailBtn.disabled = false;
                sendMailBtn.innerHTML = `<span>✈️ ${lang.send}</span>`;
                sendMailBtn.style.transform = 'scale(1)';
                
                composeModal.style.animation = 'slideOutDown 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
                setTimeout(() => {
                    composeModal.classList.add('hidden');
                    composeModal.style.animation = '';
                    clearComposeForm();
                }, 300);
            }, 500);
        });
    }
    
    // Save draft
    if (saveDraftBtn) {
        saveDraftBtn.addEventListener('click', () => {
            const lang = TRANSLATIONS[currentLanguage];
            showToast(lang.emailSaved, 'success');
            
            composeModal.style.animation = 'slideOutDown 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
            setTimeout(() => {
                composeModal.classList.add('hidden');
                composeModal.style.animation = '';
                clearComposeForm();
            }, 300);
        });
    }
    
    // AI Generate
    if (aiGenerateBtn) {
        aiGenerateBtn.addEventListener('click', async () => {
            const prompt = document.getElementById('aiPrompt')?.value.trim() || '';
            
            if (!prompt) {
                showToast('Please describe what you want to write', 'error');
                return;
            }
            
            // Show loading state
            aiGenerateBtn.disabled = true;
            aiGenerateBtn.innerHTML = '<span>🤖 Generating...</span>';
            
            const lang = TRANSLATIONS[currentLanguage];
            const aiWriting = document.querySelector('.ai-writing');
            if (aiWriting) {
                aiWriting.textContent = lang.aiWriting;
                aiWriting.style.display = 'block';
            }
            
            // Generate AI email
            const generatedEmail = await generateAIEmail(prompt);
            
            // Update preview
            document.getElementById('aiSubjectPreview').textContent = generatedEmail.subject;
            document.getElementById('aiBodyPreview').textContent = generatedEmail.body;
            
            // Show success
            aiGenerateBtn.disabled = false;
            aiGenerateBtn.innerHTML = `<span>✨ ${lang.aiGenerateBtn}</span>`;
            
            if (aiWriting) {
                aiWriting.style.display = 'none';
            }
            
            showToast(lang.aiGenerated, 'success');
        });
    }
    
    // Use AI Generated
    if (useAIGeneratedBtn) {
        useAIGeneratedBtn.addEventListener('click', () => {
            const subject = document.getElementById('aiSubjectPreview')?.textContent || '';
            const body = document.getElementById('aiBodyPreview')?.textContent || '';
            
            if (!subject || !body) {
                showToast('Please generate an email first', 'error');
                return;
            }
            
            // Copy to compose form
            document.getElementById('mailSubject').value = subject;
            document.getElementById('mailText').value = body;
            
            // Switch to compose modal
            aiComposeModal.classList.add('hidden');
            composeModal.classList.remove('hidden');
            document.getElementById('mailTo')?.focus();
            
            showToast('AI email loaded into composer', 'success');
        });
    }
}

function clearComposeForm() {
    document.getElementById('mailTo').value = '';
    document.getElementById('mailSubject').value = '';
    document.getElementById('mailText').value = '';
    document.getElementById('urgentCheck').checked = false;
}

// ==================== INITIALIZATION ====================

function initApp() {
    console.log('✅ Initializing Inbox Pro with animations...');
    
    // Load saved preferences
    const savedLang = localStorage.getItem('inboxpro-language') || 'en';
    const savedTheme = localStorage.getItem('inboxpro-theme') || 'dark';
    
    // Apply with delay for visual effect
    setTimeout(() => {
        setLanguage(savedLang);
        setTheme(savedTheme);
    }, 500);
    
    // Setup event listeners
    setupAuthForms();
    setupCompose();
    
    // Setup theme toggle
    const themeToggle = document.getElementById('themeToggle');
    const themeOptions = document.getElementById('themeOptions');
    
    if (themeToggle && themeOptions) {
        themeToggle.addEventListener('click', () => {
            themeOptions.classList.toggle('show');
            pulseAnimation(themeToggle);
        });
        
        // Close theme options when clicking outside
        document.addEventListener('click', (e) => {
            if (!themeToggle.contains(e.target) && !themeOptions.contains(e.target)) {
                themeOptions.classList.remove('show');
            }
        });
    }
    
    // Setup language selector
    document.querySelectorAll('#languageSelect, #appLanguageSelect').forEach(select => {
        select?.addEventListener('change', (e) => {
            setLanguage(e.target.value);
            pulseAnimation(e.target);
        });
    });
    
    // Setup sidebar toggle
    const menuToggle = document.getElementById('menuToggle');
    const sidebar = document.getElementById('sidebar');
    
    if (menuToggle && sidebar) {
        menuToggle.addEventListener('click', () => {
            sidebar.classList.toggle('active');
            pulseAnimation(menuToggle);
        });
    }
    
    // Setup mock auth
    mockAuth.onAuthStateChanged((user) => {
        if (user) {
            console.log('User logged in:', user.email);
            setTimeout(() => showMainApp(user), 1000);
        }
    });
    
    // Hide loading screen after animations
    setTimeout(() => {
        hideLoadingScreen();
        console.log('✅ Inbox Pro ready with animations!');
    }, 2000);
}

// Start the app
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initApp);
} else {
    initApp();
}

// Export for debugging
window.InboxPro = {
    setLanguage,
    setTheme,
    generateAIEmail,
    showToast
};
