// Inbox Pro - AI-Powered Email Client
console.log('🚀 Inbox Pro запускається...');

// ==================== CONFIGURATION ====================
const TRANSLATIONS = {
    en: {
        // Loading
        loading: "Loading Inbox Pro...",
        
        // Login Screen
        welcomeBack: "Welcome Back",
        createAccount: "Create Account",
        resetPassword: "Reset Password",
        emailAddress: "Email Address",
        password: "Password",
        fullName: "Full Name",
        confirmPassword: "Confirm Password",
        rememberMe: "Remember me",
        forgotPassword: "Forgot password?",
        signIn: "Sign In",
        newUser: "New user?",
        haveAccount: "Already have an account?",
        rememberPassword: "Remember password?",
        sendResetLink: "Send Reset Link",
        createAccountBtn: "Create Account",
        passwordHint: "Minimum 8 characters with letters & numbers",
        
        // Features
        aiSpamFilter: "AI Spam Filter",
        smartSorting: "Smart Sorting",
        securePrivate: "Secure & Private",
        
        // Main App
        aiActive: "AI Active",
        aiOrganizing: "AI is organizing your inbox. <strong>15</strong> emails sorted automatically.",
        searchPlaceholder: "Search emails, contacts, subjects...",
        compose: "Compose",
        aiCompose: "AI Compose",
        archive: "Archive",
        important: "Important",
        delete: "Delete",
        snooze: "Snooze",
        folders: "FOLDERS",
        inbox: "Inbox",
        starred: "Starred",
        sent: "Sent",
        drafts: "Drafts",
        spam: "Spam",
        trash: "Trash",
        labels: "LABELS",
        work: "Work",
        personal: "Personal",
        travel: "Travel",
        social: "Social",
        emailStats: "Email Stats",
        total: "Total",
        unread: "Unread",
        storage: "Storage",
        used: "used",
        
        // Toolbar
        newestFirst: "Newest first",
        oldestFirst: "Oldest first",
        importantFirst: "Important first",
        unreadFirst: "Unread first",
        selectAll: "Select All",
        markRead: "Mark as Read",
        withAttachments: "With Attachments",
        all: "All",
        
        // Email Viewer
        reply: "Reply",
        forward: "Forward",
        print: "Print",
        back: "Back",
        
        // Compose Modal
        newMessage: "New Message",
        to: "To",
        subject: "Subject",
        writeMessage: "Write your message here...",
        send: "Send",
        saveDraft: "Save Draft",
        importantEmail: "Important",
        aiGenerate: "AI Generate",
        aiWriting: "AI is writing your email...",
        aiPrompt: "Describe what you want to write about:",
        aiGenerateBtn: "Generate Email",
        
        // Settings
        settings: "Settings",
        profile: "Profile",
        appearance: "Appearance",
        notifications: "Notifications",
        language: "Language",
        enableNotifications: "Enable notifications",
        interfaceLanguage: "Interface Language",
        saveChanges: "Save Changes",
        
        // Quick Actions
        quickActions: "Quick Actions",
        markImportant: "Mark as Important",
        markUnread: "Mark as Unread",
        addLabel: "Add Label",
        moveToFolder: "Move to Folder",
        
        // Mobile
        mobileCompose: "Compose",
        mobileSearch: "Search",
        mobileInbox: "Inbox",
        mobileStarred: "Starred",
        mobileSent: "Sent",
        mobileMore: "More",
        
        // Toast Messages
        loginSuccess: "Login successful! Welcome to Inbox Pro.",
        registerSuccess: "Account created successfully!",
        emailSent: "Email sent successfully!",
        emailSaved: "Draft saved successfully!",
        aiGenerated: "Email generated by AI!",
        themeChanged: "Theme changed to",
        languageChanged: "Language changed to",
        swipeInstruction: "Swipe left/right for actions",
        installPrompt: "Install Inbox Pro for better experience"
    },
    
    ua: {
        loading: "Завантаження Inbox Pro...",
        welcomeBack: "З поверненням",
        createAccount: "Створити акаунт",
        resetPassword: "Скинути пароль",
        emailAddress: "Електронна адреса",
        password: "Пароль",
        fullName: "Повне ім'я",
        confirmPassword: "Підтвердіть пароль",
        rememberMe: "Запам'ятати мене",
        forgotPassword: "Забули пароль?",
        signIn: "Увійти",
        newUser: "Новий користувач?",
        haveAccount: "Вже маєте акаунт?",
        rememberPassword: "Пам'ятаєте пароль?",
        sendResetLink: "Надіслати посилання",
        createAccountBtn: "Створити акаунт",
        passwordHint: "Мінімум 8 символів з літерами та цифрами",
        
        aiSpamFilter: "AI Фільтр Спаму",
        smartSorting: "Розумне Сортування",
        securePrivate: "Захищено & Приватно",
        
        aiActive: "AI Активний",
        aiOrganizing: "AI організовує вашу пошту. <strong>15</strong> листів відсортовано автоматично.",
        searchPlaceholder: "Пошук листів, контактів, тем...",
        compose: "Написати",
        aiCompose: "AI Написати",
        archive: "Архівувати",
        important: "Важливе",
        delete: "Видалити",
        snooze: "Відкласти",
        folders: "ПАПКИ",
        inbox: "Вхідні",
        starred: "Зірочка",
        sent: "Надіслані",
        drafts: "Чернетки",
        spam: "Спам",
        trash: "Кошик",
        labels: "МІТКИ",
        work: "Робота",
        personal: "Особисте",
        travel: "Подорожі",
        social: "Соціальне",
        emailStats: "Статистика",
        total: "Всього",
        unread: "Непрочитані",
        storage: "Сховище",
        used: "використано",
        
        newestFirst: "Спочатку нові",
        oldestFirst: "Спочатку старі",
        importantFirst: "Спочатку важливі",
        unreadFirst: "Спочатку непрочитані",
        selectAll: "Вибрати все",
        markRead: "Позначити прочитаним",
        withAttachments: "З файлами",
        all: "Всі",
        
        reply: "Відповісти",
        forward: "Переслати",
        print: "Друк",
        back: "Назад",
        
        newMessage: "Нове повідомлення",
        to: "Кому",
        subject: "Тема",
        writeMessage: "Напишіть ваше повідомлення тут...",
        send: "Надіслати",
        saveDraft: "Зберегти чернетку",
        importantEmail: "Важливо",
        aiGenerate: "AI Згенерувати",
        aiWriting: "AI пише ваш лист...",
        aiPrompt: "Опишіть, про що хочете написати:",
        aiGenerateBtn: "Згенерувати Лист",
        
        settings: "Налаштування",
        profile: "Профіль",
        appearance: "Зовнішній вигляд",
        notifications: "Сповіщення",
        language: "Мова",
        enableNotifications: "Увімкнути сповіщення",
        interfaceLanguage: "Мова інтерфейсу",
        saveChanges: "Зберегти зміни",
        
        quickActions: "Швидкі дії",
        markImportant: "Позначити важливим",
        markUnread: "Позначити непрочитаним",
        addLabel: "Додати мітку",
        moveToFolder: "Перемістити в папку",
        
        mobileCompose: "Написати",
        mobileSearch: "Пошук",
        mobileInbox: "Вхідні",
        mobileStarred: "Зірочка",
        mobileSent: "Надіслані",
        mobileMore: "Більше",
        
        loginSuccess: "Вхід успішний! Ласкаво просимо до Inbox Pro.",
        registerSuccess: "Акаунт успішно створено!",
        emailSent: "Лист успішно відправлено!",
        emailSaved: "Чернетку успішно збережено!",
        aiGenerated: "Лист згенеровано AI!",
        themeChanged: "Тему змінено на",
        languageChanged: "Мову змінено на",
        swipeInstruction: "Проведіть пальцем вліво/вправо для дій",
        installPrompt: "Встановіть Inbox Pro для кращого досвіду"
    }
};

// Mock authentication
const mockAuth = {
    onAuthStateChanged: (callback) => {
        setTimeout(() => callback(null), 1000);
    },
    
    login: async (email, password) => {
        await new Promise(resolve => setTimeout(resolve, 1000));
        return { uid: 'mock-user', email, displayName: 'Test User' };
    },
    
    register: async (email, password, name) => {
        await new Promise(resolve => setTimeout(resolve, 1000));
        return { uid: 'mock-user', email, displayName: name };
    },
    
    logout: async () => {
        await new Promise(resolve => setTimeout(resolve, 500));
    },
    
    resetPassword: async (email) => {
        await new Promise(resolve => setTimeout(resolve, 1000));
    }
};

// State
let currentLanguage = 'en';
let currentTheme = 'dark';
let currentUser = null;
let deferredPrompt = null;
let isMobile = false;
let isTouchDevice = false;
let swipeStartX = 0;
let swipeStartY = 0;
let swipeThreshold = 50;

// ==================== CORE FUNCTIONS ====================

function hideLoadingScreen() {
    const loadingOverlay = document.getElementById('initialLoading');
    if (loadingOverlay) {
        loadingOverlay.style.opacity = '0';
        loadingOverlay.style.transition = 'opacity 0.5s cubic-bezier(0.4, 0, 0.2, 1)';
        setTimeout(() => {
            loadingOverlay.style.display = 'none';
        }, 500);
    }
}

function showToast(message, type = 'info', duration = 5000) {
    const toastContainer = document.getElementById('toastContainer');
    if (!toastContainer) return;
    
    const toast = document.createElement('div');
    toast.className = `toast ${type}`;
    toast.style.animation = 'toastSlideIn 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
    
    const icons = {
        success: '✅',
        error: '❌',
        warning: '⚠️',
        info: 'ℹ️'
    };
    
    toast.innerHTML = `
        <span class="toast-icon">${icons[type] || 'ℹ️'}</span>
        <div class="toast-content">
            <div class="toast-message">${message}</div>
        </div>
        <button class="toast-close">✕</button>
    `;
    
    toastContainer.appendChild(toast);
    
    // Mobile vibration for notifications
    if (isMobile && type === 'success') {
        vibrate([100]);
    }
    
    toast.querySelector('.toast-close').addEventListener('click', () => {
        toast.style.animation = 'toastSlideOut 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
        setTimeout(() => toast.remove(), 300);
    });
    
    setTimeout(() => {
        if (toast.parentNode) {
            toast.style.animation = 'toastSlideOut 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
            setTimeout(() => toast.remove(), 300);
        }
    }, duration);
}

// ==================== MOBILE FUNCTIONS ====================

function checkMobile() {
    isMobile = window.innerWidth <= 768;
    isTouchDevice = 'ontouchstart' in window || navigator.maxTouchPoints > 0;
    
    // Update UI based on device
    updateMobileUI();
    
    // Show swipe instruction on first load
    const hasSeenSwipe = localStorage.getItem('hasSeenSwipe');
    if (isMobile && !hasSeenSwipe && isTouchDevice) {
        setTimeout(() => {
            showSwipeInstruction();
        }, 2000);
    }
}

function updateMobileUI() {
    const sidebar = document.getElementById('sidebar');
    const mobileNav = document.getElementById('mobileNav');
    const mobileHeaderActions = document.querySelector('.mobile-header-actions');
    const mobileActionsBar = document.querySelector('.mobile-actions-bar');
    
    if (isMobile) {
        // Hide sidebar, show mobile nav
        if (sidebar) sidebar.classList.remove('active');
        if (mobileNav) mobileNav.style.display = 'flex';
        if (mobileHeaderActions) mobileHeaderActions.style.display = 'flex';
        if (mobileActionsBar) mobileActionsBar.style.display = 'flex';
        
        // Update mobile labels
        updateMobileLabels();
    } else {
        // Show sidebar, hide mobile nav
        if (mobileNav) mobileNav.style.display = 'none';
        if (mobileHeaderActions) mobileHeaderActions.style.display = 'none';
        if (mobileActionsBar) mobileActionsBar.style.display = 'none';
    }
}

function updateMobileLabels() {
    const lang = TRANSLATIONS[currentLanguage];
    
    // Update mobile navigation labels
    const mobileNavItems = document.querySelectorAll('.mobile-nav-item');
    mobileNavItems.forEach(item => {
        const action = item.dataset.action;
        const label = item.querySelector('.nav-label');
        
        if (label) {
            switch(action) {
                case 'inbox': label.textContent = lang.mobileInbox; break;
                case 'starred': label.textContent = lang.mobileStarred; break;
                case 'sent': label.textContent = lang.mobileSent; break;
                case 'more': label.textContent = lang.mobileMore; break;
            }
        }
    });
}

function showSwipeInstruction() {
    const swipeInstruction = document.getElementById('swipeInstruction');
    if (swipeInstruction) {
        swipeInstruction.style.display = 'flex';
        setTimeout(() => {
            swipeInstruction.style.opacity = '0';
            setTimeout(() => {
                swipeInstruction.style.display = 'none';
                swipeInstruction.style.opacity = '1';
                localStorage.setItem('hasSeenSwipe', 'true');
            }, 300);
        }, 3000);
    }
}

function setupSwipeGestures() {
    if (!isTouchDevice) return;
    
    const emailItems = document.querySelectorAll('.email-item');
    
    emailItems.forEach(item => {
        let startX = 0;
        let startY = 0;
        let isSwiping = false;
        
        item.addEventListener('touchstart', (e) => {
            startX = e.touches[0].clientX;
            startY = e.touches[0].clientY;
            isSwiping = false;
        }, { passive: true });
        
        item.addEventListener('touchmove', (e) => {
            if (!startX || !startY) return;
            
            const x = e.touches[0].clientX;
            const y = e.touches[0].clientY;
            
            const diffX = x - startX;
            const diffY = y - startY;
            
            // Check if it's a horizontal swipe (not vertical scroll)
            if (Math.abs(diffX) > Math.abs(diffY) * 2) {
                e.preventDefault();
                isSwiping = true;
                
                // Add visual feedback
                item.style.transform = `translateX(${diffX}px)`;
                item.classList.remove('swipe-right', 'swipe-left');
                
                if (diffX > 0) {
                    item.classList.add('swipe-right');
                } else {
                    item.classList.add('swipe-left');
                }
            }
        }, { passive: false });
        
        item.addEventListener('touchend', (e) => {
            if (!isSwiping) return;
            
            const endX = e.changedTouches[0].clientX;
            const diffX = endX - startX;
            
            // Reset transform
            item.style.transform = '';
            item.classList.remove('swipe-right', 'swipe-left');
            
            // Check if swipe threshold is reached
            if (Math.abs(diffX) > swipeThreshold) {
                if (diffX > 0) {
                    // Swipe right - Archive
                    handleSwipeAction(item, 'archive');
                } else {
                    // Swipe left - Delete
                    handleSwipeAction(item, 'delete');
                }
                
                // Haptic feedback on mobile
                vibrate([50]);
            }
            
            startX = 0;
            startY = 0;
            isSwiping = false;
        });
    });
}

function handleSwipeAction(emailItem, action) {
    const lang = TRANSLATIONS[currentLanguage];
    
    switch(action) {
        case 'archive':
            emailItem.style.animation = 'slideOutLeft 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
            setTimeout(() => {
                emailItem.remove();
                showToast('Email archived', 'success');
            }, 300);
            break;
            
        case 'delete':
            emailItem.style.animation = 'slideOutRight 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
            setTimeout(() => {
                emailItem.remove();
                showToast('Email deleted', 'success');
            }, 300);
            break;
    }
}

function vibrate(pattern) {
    if (isMobile && navigator.vibrate) {
        navigator.vibrate(pattern);
    }
}

// ==================== PWA FUNCTIONS ====================

function setupPWA() {
    // Check if PWA is already installed
    if (window.matchMedia('(display-mode: standalone)').matches) {
        console.log('PWA installed and running in standalone mode');
        document.getElementById('installPrompt')?.style.display = 'none';
    }
    
    // Listen for beforeinstallprompt event
    window.addEventListener('beforeinstallprompt', (e) => {
        e.preventDefault();
        deferredPrompt = e;
        
        // Show install prompt
        const installPrompt = document.getElementById('installPrompt');
        if (installPrompt) {
            installPrompt.style.display = 'block';
            
            const installBtn = document.getElementById('installBtn');
            if (installBtn) {
                installBtn.addEventListener('click', async () => {
                    if (!deferredPrompt) return;
                    
                    deferredPrompt.prompt();
                    const { outcome } = await deferredPrompt.userChoice;
                    
                    if (outcome === 'accepted') {
                        showToast('Inbox Pro will be installed shortly', 'success');
                        installPrompt.style.display = 'none';
                    }
                    
                    deferredPrompt = null;
                });
            }
        }
    });
    
    // Listen for app installed event
    window.addEventListener('appinstalled', () => {
        console.log('PWA installed successfully');
        document.getElementById('installPrompt')?.style.display = 'none';
        deferredPrompt = null;
    });
}

// ==================== ANIMATION FUNCTIONS ====================

function animateElement(element, animationName, duration = 300) {
    return new Promise(resolve => {
        element.style.animation = `${animationName} ${duration}ms cubic-bezier(0.4, 0, 0.2, 1)`;
        setTimeout(() => {
            element.style.animation = '';
            resolve();
        }, duration);
    });
}

function pulseAnimation(element) {
    element.style.transform = 'scale(1)';
    element.style.transition = 'transform 0.2s cubic-bezier(0.4, 0, 0.2, 1)';
    
    setTimeout(() => {
        element.style.transform = 'scale(1.05)';
    }, 10);
    
    setTimeout(() => {
        element.style.transform = 'scale(1)';
    }, 200);
}

function slideIn(element, direction = 'right') {
    const directions = {
        right: 'translateX(30px)',
        left: 'translateX(-30px)',
        up: 'translateY(30px)',
        down: 'translateY(-30px)'
    };
    
    element.style.opacity = '0';
    element.style.transform = directions[direction] || directions.right;
    element.style.transition = 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
    
    setTimeout(() => {
        element.style.opacity = '1';
        element.style.transform = 'translate(0, 0)';
    }, 10);
}

// ==================== THEME SYSTEM ====================

function setTheme(theme) {
    const oldTheme = currentTheme;
    currentTheme = theme;
    localStorage.setItem('inboxpro-theme', theme);
    
    // Smooth theme transition
    document.body.style.transition = 'background-color 0.5s cubic-bezier(0.4, 0, 0.2, 1), color 0.5s cubic-bezier(0.4, 0, 0.2, 1)';
    document.body.className = theme + '-theme';
    
    // Update theme icon with animation
    const themeIcon = document.querySelector('.theme-icon');
    if (themeIcon) {
        themeIcon.style.transform = 'rotate(180deg) scale(0.8)';
        themeIcon.style.transition = 'transform 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
        
        setTimeout(() => {
            themeIcon.textContent = theme === 'light' ? '☀️' : theme === 'dark' ? '🌙' : '●';
            themeIcon.style.transform = 'rotate(0deg) scale(1)';
        }, 150);
    }
    
    // Update theme buttons
    document.querySelectorAll('.theme-option, .theme-btn').forEach(btn => {
        btn.classList.remove('active');
        if (btn.dataset.theme === theme) {
            btn.classList.add('active');
            pulseAnimation(btn);
        }
    });
    
    // Show toast
    const lang = TRANSLATIONS[currentLanguage];
    showToast(`${lang.themeChanged} ${theme}`, 'success');
    
    // Reset transition
    setTimeout(() => {
        document.body.style.transition = '';
    }, 500);
}

// ==================== LANGUAGE SYSTEM ====================

function setLanguage(lang) {
    if (!TRANSLATIONS[lang]) lang = 'en';
    
    currentLanguage = lang;
    localStorage.setItem('inboxpro-language', lang);
    
    // Update language selectors
    document.querySelectorAll('#languageSelect, #appLanguageSelect, #settingsLanguage').forEach(select => {
        if (select) select.value = lang;
    });
    
    // Update all text elements
    updateTextElements();
    
    // Show toast
    const langNames = { en: 'English', ua: 'Українська', de: 'Deutsch', ru: 'Русский' };
    showToast(`${TRANSLATIONS[lang].languageChanged} ${langNames[lang]}`, 'success');
}

function updateTextElements() {
    const lang = TRANSLATIONS[currentLanguage];
    
    // Helper function to update text
    function updateText(selector, text) {
        const element = document.querySelector(selector);
        if (element) element.textContent = text;
    }
    
    function updatePlaceholder(selector, text) {
        const element = document.querySelector(selector);
        if (element) element.placeholder = text;
    }
    
    // Loading
    updateText('#loadingText', lang.loading);
    
    // Login Form
    updateText('#loginForm h2', `🔑 ${lang.welcomeBack}`);
    updateText('#registerForm h2', `👤 ${lang.createAccount}`);
    updateText('#resetForm h2', `🔑 ${lang.resetPassword}`);
    
    updateText('label[for="loginEmail"]', lang.emailAddress);
    updateText('label[for="loginPassword"]', lang.password);
    updateText('label[for="registerName"]', lang.fullName);
    updateText('label[for="registerEmail"]', lang.emailAddress);
    updateText('label[for="registerPassword"]', lang.password);
    updateText('label[for="registerConfirm"]', lang.confirmPassword);
    updateText('label[for="resetEmail"]', lang.emailAddress);
    
    updatePlaceholder('#loginEmail', 'your@email.com');
    updatePlaceholder('#loginPassword', '••••••••');
    updatePlaceholder('#registerName', lang.fullName);
    updatePlaceholder('#registerEmail', 'your@email.com');
    updatePlaceholder('#registerPassword', '••••••••');
    updatePlaceholder('#registerConfirm', '••••••••');
    updatePlaceholder('#resetEmail', 'your@email.com');
    
    updateText('#rememberMeText', lang.rememberMe);
    updateText('#newUserText', lang.newUser);
    updateText('#haveAccountText', lang.haveAccount);
    updateText('#rememberPasswordText', lang.rememberPassword);
    
    updateText('#loginBtn .btn-text', lang.signIn);
    updateText('#registerBtn .btn-text', lang.createAccountBtn);
    updateText('#sendResetBtn .btn-text', lang.sendResetLink);
    
    updateText('.password-hint', lang.passwordHint);
    
    // Features
    const features = document.querySelectorAll('.feature-text');
    if (features.length >= 3) {
        features[0].textContent = lang.aiSpamFilter;
        features[1].textContent = lang.smartSorting;
        features[2].textContent = lang.securePrivate;
    }
    
    // Main App
    updateText('.ai-text', lang.aiActive);
    updateText('.compose-text', lang.compose);
    updateText('.ai-compose-text', lang.aiCompose);
    
    const quickLabels = document.querySelectorAll('.quick-label');
    if (quickLabels.length >= 4) {
        quickLabels[0].textContent = lang.archive;
        quickLabels[1].textContent = lang.important;
        quickLabels[2].textContent = lang.delete;
        quickLabels[3].textContent = lang.snooze;
    }
    
    updateText('.nav-title:first-child', lang.folders);
    updateText('[data-folder="inbox"] .nav-text', lang.inbox);
    updateText('[data-folder="starred"] .nav-text', lang.starred);
    updateText('[data-folder="sent"] .nav-text', lang.sent);
    updateText('[data-folder="drafts"] .nav-text', lang.drafts);
    updateText('[data-folder="spam"] .nav-text', lang.spam);
    updateText('[data-folder="trash"] .nav-text', lang.trash);
    
    updateText('.nav-title:nth-child(3)', lang.labels);
    updateText('[data-label="work"] .label-text', lang.work);
    updateText('[data-label="personal"] .label-text', lang.personal);
    updateText('[data-label="travel"] .label-text', lang.travel);
    updateText('[data-label="social"] .label-text', lang.social);
    
    updateText('.stat-title', lang.emailStats);
    updateText('.stat-label:nth-child(1)', lang.total);
    updateText('.stat-label:nth-child(2)', lang.unread);
    updateText('.stat-label:nth-child(3)', lang.important);
    
    updateText('.storage-title', lang.storage);
    updateText('.storage-info', `4.2GB / 10GB ${lang.used}`);
    
    // Search
    updatePlaceholder('#searchInput', lang.searchPlaceholder);
    
    // Sort options
    const sortSelect = document.getElementById('sortSelect');
    if (sortSelect && sortSelect.children.length >= 4) {
        sortSelect.children[0].textContent = lang.newestFirst;
        sortSelect.children[1].textContent = lang.oldestFirst;
        sortSelect.children[2].textContent = lang.importantFirst;
        sortSelect.children[3].textContent = lang.unreadFirst;
    }
    
    // Filter tags
    const filterTags = document.querySelectorAll('.filter-tag');
    if (filterTags.length >= 4) {
        filterTags[0].querySelector('span:first-child').textContent = lang.all;
        filterTags[1].querySelector('span:first-child').textContent = `${lang.unread}`;
        filterTags[2].querySelector('span:first-child').textContent = `★ ${lang.starred}`;
        filterTags[3].querySelector('span:first-child').textContent = `📎 ${lang.withAttachments}`;
    }
    
    // AI Message
    const aiMessage = document.querySelector('.ai-message');
    if (aiMessage) {
        aiMessage.innerHTML = lang.aiOrganizing;
    }
    
    // Install prompt
    const installText = document.querySelector('.install-text');
    if (installText) {
        installText.textContent = lang.installPrompt;
    }
    
    // Update mobile labels
    if (isMobile) {
        updateMobileLabels();
    }
}

// ==================== AI EMAIL WRITER ====================

async function generateAIEmail(prompt) {
    // Mock AI generation with realistic email examples
    const examples = {
        business: {
            subject: "Meeting Follow-up & Action Items",
            body: `Dear Team,

Following up on our meeting earlier today, here are the key action items:

1. Complete the Q3 reports by Friday
2. Schedule client demo for next week
3. Update project documentation

Let me know if you have any questions.

Best regards,
[Your Name]`
        },
        casual: {
            subject: "Quick update",
            body: `Hey there!

Just wanted to share a quick update about the project. Everything is progressing well and we're on track for the deadline.

Let me know if you need anything from my end.

Cheers!`
        },
        formal: {
            subject: "Formal Inquiry Regarding Your Services",
            body: `To Whom It May Concern,

I am writing to inquire about your services. Could you please provide more information regarding:

1. Pricing structure
2. Service availability
3. Implementation timeline

Thank you for your attention to this matter.

Sincerely,
[Your Name]`
        },
        meeting: {
            subject: "Meeting Request - [Topic]",
            body: `Hi [Name],

I hope this email finds you well.

I'd like to schedule a meeting to discuss [topic]. Would you be available sometime next week?

Please let me know what time works best for you.

Looking forward to connecting!

Best regards,
[Your Name]`
        },
        followup: {
            subject: "Following up on our conversation",
            body: `Hi [Name],

Just following up on our conversation from [date]. I wanted to check if you had a chance to [action item].

Let me know if you need any additional information from my side.

Thanks,
[Your Name]`
        },
        thankyou: {
            subject: "Thank you!",
            body: `Dear [Name],

Thank you so much for [reason]. I truly appreciate your [specific action or quality].

It was a pleasure working with you, and I look forward to our future collaboration.

Warm regards,
[Your Name]`
        },
        introduction: {
            subject: "Introduction - [Your Name]",
            body: `Hello [Name],

My name is [Your Name] and I'm [your position/role] at [your company]. I'm reaching out because [reason for introduction].

I'd love to connect and learn more about your work in [their field].

Best regards,
[Your Name]`
        }
    };
    
    // Simple keyword matching
    let emailType = 'business';
    const promptLower = prompt.toLowerCase();
    
    if (promptLower.includes('casual') || promptLower.includes('friendly') || promptLower.includes('quick')) {
        emailType = 'casual';
    } else if (promptLower.includes('formal') || promptLower.includes('official') || promptLower.includes('inquiry')) {
        emailType = 'formal';
    } else if (promptLower.includes('meeting') || promptLower.includes('schedule')) {
        emailType = 'meeting';
    } else if (promptLower.includes('follow') || promptLower.includes('check')) {
        emailType = 'followup';
    } else if (promptLower.includes('thank') || promptLower.includes('appreciate')) {
        emailType = 'thankyou';
    } else if (promptLower.includes('introduc') || promptLower.includes('connect')) {
        emailType = 'introduction';
    }
    
    // Simulate AI thinking delay
    await new Promise(resolve => setTimeout(resolve, 1500));
    
    return examples[emailType];
}

// ==================== QUICK ACTIONS SYSTEM ====================

function setupQuickActions() {
    const emailItems = document.querySelectorAll('.email-item');
    
    emailItems.forEach(item => {
        // Add hover effects for desktop
        if (!isMobile) {
            item.addEventListener('mouseenter', () => {
                item.style.transform = 'translateX(8px)';
                item.style.transition = 'transform 0.2s cubic-bezier(0.4, 0, 0.2, 1)';
            });
            
            item.addEventListener('mouseleave', () => {
                item.style.transform = 'translateX(0)';
            });
        }
        
        // Add context menu for desktop
        if (!isMobile) {
            item.addEventListener('contextmenu', (e) => {
                e.preventDefault();
                showQuickActionsMenu(e, item);
            });
        }
        
        // Touch handling for mobile
        if (isMobile && isTouchDevice) {
            let tapTimer;
            let longPress = false;
            
            item.addEventListener('touchstart', () => {
                tapTimer = setTimeout(() => {
                    longPress = true;
                    showQuickActionsMenuTouch(item);
                    vibrate([100]);
                }, 500);
            });
            
            item.addEventListener('touchend', () => {
                clearTimeout(tapTimer);
                if (!longPress) {
                    // Normal tap - view email
                    viewEmail(item);
                }
                longPress = false;
            });
            
            item.addEventListener('touchmove', () => {
                clearTimeout(tapTimer);
                longPress = false;
            });
        } else {
            // Desktop click to view
            item.addEventListener('click', (e) => {
                if (e.target.type !== 'checkbox' && !e.target.closest('.email-action')) {
                    viewEmail(item);
                }
            });
        }
    });
    
    // Keyboard shortcuts for desktop
    if (!isMobile) {
        document.addEventListener('keydown', (e) => {
            // Ctrl/Cmd + S to star
            if ((e.ctrlKey || e.metaKey) && e.key === 's') {
                e.preventDefault();
                const selected = document.querySelector('.email-item:hover');
                if (selected) {
                    const starBtn = selected.querySelector('.star-btn');
                    if (starBtn) {
                        starBtn.click();
                        showToast('Email starred', 'success');
                    }
                }
            }
            
            // Ctrl/Cmd + D to delete
            if ((e.ctrlKey || e.metaKey) && e.key === 'd') {
                e.preventDefault();
                const selected = document.querySelector('.email-item:hover');
                if (selected) {
                    selected.style.animation = 'slideOutRight 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
                    setTimeout(() => {
                        selected.remove();
                        showToast('Email deleted', 'success');
                    }, 300);
                }
            }
            
            // Ctrl/Cmd + A to archive
            if ((e.ctrlKey || e.metaKey) && e.key === 'a') {
                e.preventDefault();
                const selected = document.querySelector('.email-item:hover');
                if (selected) {
                    selected.style.animation = 'slideOutLeft 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
                    setTimeout(() => {
                        selected.remove();
                        showToast('Email archived', 'success');
                    }, 300);
                }
            }
        });
    }
}

function showQuickActionsMenu(e, emailItem) {
    // Remove existing menu
    const existingMenu = document.querySelector('.quick-actions-menu');
    if (existingMenu) existingMenu.remove();
    
    const lang = TRANSLATIONS[currentLanguage];
    
    const menu = document.createElement('div');
    menu.className = 'quick-actions-menu';
    menu.style.left = e.pageX + 'px';
    menu.style.top = e.pageY + 'px';
    menu.style.animation = 'scaleIn 0.2s cubic-bezier(0.4, 0, 0.2, 1)';
    
    menu.innerHTML = `
        <div class="quick-actions-header">
            <span>${lang.quickActions}</span>
        </div>
        <button class="quick-action-item" data-action="star">
            <span class="action-icon">★</span>
            <span>${lang.markImportant}</span>
        </button>
        <button class="quick-action-item" data-action="unread">
            <span class="action-icon">📨</span>
            <span>${lang.markUnread}</span>
        </button>
        <button class="quick-action-item" data-action="label">
            <span class="action-icon">🏷️</span>
            <span>${lang.addLabel}</span>
        </button>
        <button class="quick-action-item" data-action="move">
            <span class="action-icon">📁</span>
            <span>${lang.moveToFolder}</span>
        </button>
    `;
    
    document.body.appendChild(menu);
    
    // Handle menu actions
    menu.querySelectorAll('.quick-action-item').forEach(button => {
        button.addEventListener('click', () => {
            const action = button.dataset.action;
            handleQuickAction(action, emailItem);
            menu.remove();
        });
    });
    
    // Close menu when clicking outside
    setTimeout(() => {
        const closeMenu = (clickEvent) => {
            if (!menu.contains(clickEvent.target)) {
                menu.style.animation = 'scaleOut 0.2s cubic-bezier(0.4, 0, 0.2, 1)';
                setTimeout(() => menu.remove(), 200);
                document.removeEventListener('click', closeMenu);
            }
        };
        document.addEventListener('click', closeMenu);
    }, 100);
}

function showQuickActionsMenuTouch(emailItem) {
    const lang = TRANSLATIONS[currentLanguage];
    
    // Create mobile action sheet
    const actionSheet = document.createElement('div');
    actionSheet.className = 'mobile-action-sheet';
    actionSheet.innerHTML = `
        <div class="action-sheet-header">
            <span>${lang.quickActions}</span>
            <button class="action-sheet-close">✕</button>
        </div>
        <div class="action-sheet-actions">
            <button class="action-sheet-item" data-action="star">
                <span class="action-icon">★</span>
                <span>${lang.markImportant}</span>
            </button>
            <button class="action-sheet-item" data-action="unread">
                <span class="action-icon">📨</span>
                <span>${lang.markUnread}</span>
            </button>
            <button class="action-sheet-item" data-action="label">
                <span class="action-icon">🏷️</span>
                <span>${lang.addLabel}</span>
            </button>
            <button class="action-sheet-item" data-action="move">
                <span class="action-icon">📁</span>
                <span>${lang.moveToFolder}</span>
            </button>
            <button class="action-sheet-item delete" data-action="delete">
                <span class="action-icon">🗑️</span>
                <span>${lang.delete}</span>
            </button>
        </div>
    `;
    
    document.body.appendChild(actionSheet);
    
    // Animate in
    setTimeout(() => {
        actionSheet.style.transform = 'translateY(0)';
    }, 10);
    
    // Handle actions
    actionSheet.querySelectorAll('.action-sheet-item').forEach(button => {
        button.addEventListener('click', () => {
            const action = button.dataset.action;
            handleQuickAction(action, emailItem);
            closeActionSheet(actionSheet);
        });
    });
    
    // Close button
    actionSheet.querySelector('.action-sheet-close').addEventListener('click', () => {
        closeActionSheet(actionSheet);
    });
    
    // Close on backdrop click
    actionSheet.addEventListener('click', (e) => {
        if (e.target === actionSheet) {
            closeActionSheet(actionSheet);
        }
    });
}

function closeActionSheet(actionSheet) {
    actionSheet.style.transform = 'translateY(100%)';
    setTimeout(() => {
        actionSheet.remove();
    }, 300);
}

function handleQuickAction(action, emailItem) {
    const lang = TRANSLATIONS[currentLanguage];
    
    switch(action) {
        case 'star':
            const starBtn = emailItem.querySelector('.star-btn');
            if (starBtn) {
                starBtn.classList.toggle('active');
                starBtn.textContent = starBtn.classList.contains('active') ? '★' : '☆';
                pulseAnimation(starBtn);
                showToast('Email starred', 'success');
            }
            break;
            
        case 'unread':
            emailItem.classList.toggle('unread');
            showToast('Email marked as unread', 'success');
            break;
            
        case 'label':
            showToast('Label added', 'info');
            break;
            
        case 'move':
            showToast('Email moved', 'info');
            break;
            
        case 'delete':
            emailItem.style.animation = 'slideOutRight 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
            setTimeout(() => {
                emailItem.remove();
                showToast('Email deleted', 'success');
            }, 300);
            break;
    }
}

function viewEmail(emailItem) {
    const emailList = document.getElementById('emailsList');
    const emailViewer = document.getElementById('emailViewer');
    
    if (emailList && emailViewer) {
        emailList.style.display = 'none';
        emailViewer.style.display = 'flex';
        
        // Show mobile viewer actions on mobile
        if (isMobile) {
            const mobileViewerActions = document.querySelector('.mobile-viewer-actions');
            if (mobileViewerActions) {
                mobileViewerActions.style.display = 'flex';
            }
        }
    }
}

// ==================== EVENT HANDLERS ====================

function setupAuthForms() {
    // Form switching
    const showRegisterBtn = document.getElementById('showRegister');
    const showLoginBtn = document.getElementById('showLogin');
    const showLoginFromResetBtn = document.getElementById('showLoginFromReset');
    const forgotPasswordBtn = document.getElementById('forgotPasswordBtn');
    
    const loginForm = document.getElementById('loginForm');
    const registerForm = document.getElementById('registerForm');
    const resetForm = document.getElementById('resetForm');
    
    // Switch forms with animation
    [showRegisterBtn, showLoginBtn, forgotPasswordBtn, showLoginFromResetBtn].forEach((btn, index) => {
        if (!btn) return;
        
        btn.addEventListener('click', (e) => {
            e.preventDefault();
            
            // Hide all forms
            [loginForm, registerForm, resetForm].forEach(form => {
                if (form) {
                    form.style.opacity = '0';
                    form.style.transform = 'translateY(10px)';
                    form.style.transition = 'all 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
                    setTimeout(() => {
                        form.classList.remove('active');
                    }, 150);
                }
            });
            
            // Show target form with animation
            setTimeout(() => {
                let targetForm;
                if (btn === showRegisterBtn) targetForm = registerForm;
                else if (btn === showLoginBtn || btn === showLoginFromResetBtn) targetForm = loginForm;
                else if (btn === forgotPasswordBtn) targetForm = resetForm;
                
                if (targetForm) {
                    targetForm.classList.add('active');
                    setTimeout(() => {
                        targetForm.style.opacity = '1';
                        targetForm.style.transform = 'translateY(0)';
                    }, 10);
                }
            }, 150);
        });
    });
    
    // Login button
    const loginBtn = document.getElementById('loginBtn');
    if (loginBtn) {
        loginBtn.addEventListener('click', async () => {
            const email = document.getElementById('loginEmail')?.value.trim();
            const password = document.getElementById('loginPassword')?.value;
            
            if (!email || !password) {
                showToast('Please fill in all fields', 'error');
                return;
            }
            
            try {
                loginBtn.disabled = true;
                loginBtn.innerHTML = '<span class="btn-text">Signing in...</span><span class="btn-icon">⏳</span>';
                loginBtn.style.transform = 'scale(0.98)';
                
                const user = await mockAuth.login(email, password);
                
                // Success animation
                loginBtn.style.transform = 'scale(1)';
                loginBtn.style.background = 'linear-gradient(135deg, #10b981, #059669)';
                
                const lang = TRANSLATIONS[currentLanguage];
                showToast(lang.loginSuccess, 'success');
                
                // Show main app with delay
                setTimeout(() => showMainApp(user), 1000);
                
            } catch (error) {
                showToast('Login failed. Please try again.', 'error');
                loginBtn.disabled = false;
                const lang = TRANSLATIONS[currentLanguage];
                loginBtn.innerHTML = `<span class="btn-text">${lang.signIn}</span><span class="btn-icon">→</span>`;
                loginBtn.style.transform = 'scale(1)';
                loginBtn.style.background = '';
            }
        });
    }
    
    // Register button
    const registerBtn = document.getElementById('registerBtn');
    if (registerBtn) {
        registerBtn.addEventListener('click', async () => {
            const name = document.getElementById('registerName')?.value.trim();
            const email = document.getElementById('registerEmail')?.value.trim();
            const password = document.getElementById('registerPassword')?.value;
            const confirm = document.getElementById('registerConfirm')?.value;
            
            if (!name || !email || !password || !confirm) {
                showToast('Please fill in all fields', 'error');
                return;
            }
            
            if (password !== confirm) {
                showToast('Passwords do not match', 'error');
                return;
            }
            
            if (password.length < 8) {
                showToast('Password must be at least 8 characters', 'error');
                return;
            }
            
            try {
                registerBtn.disabled = true;
                registerBtn.innerHTML = '<span class="btn-text">Creating account...</span><span class="btn-icon">⏳</span>';
                registerBtn.style.transform = 'scale(0.98)';
                
                const user = await mockAuth.register(email, password, name);
                
                // Success animation
                registerBtn.style.transform = 'scale(1)';
                registerBtn.style.background = 'linear-gradient(135deg, #10b981, #059669)';
                
                const lang = TRANSLATIONS[currentLanguage];
                showToast(lang.registerSuccess, 'success');
                
                // Show main app with delay
                setTimeout(() => showMainApp(user), 1000);
                
            } catch (error) {
                showToast('Registration failed. Please try again.', 'error');
                registerBtn.disabled = false;
                const lang = TRANSLATIONS[currentLanguage];
                registerBtn.innerHTML = `<span class="btn-text">${lang.createAccountBtn}</span><span class="btn-icon">✓</span>`;
                registerBtn.style.transform = 'scale(1)';
                registerBtn.style.background = '';
            }
        });
    }
    
    // Password strength indicator
    const passwordInput = document.getElementById('registerPassword');
    if (passwordInput) {
        passwordInput.addEventListener('input', updatePasswordStrength);
    }
}

function updatePasswordStrength() {
    const password = document.getElementById('registerPassword')?.value || '';
    const strengthMeter = document.querySelector('.password-strength-meter');
    if (!strengthMeter) return;
    
    let strength = 0;
    if (password.length >= 8) strength++;
    if (/[A-Z]/.test(password)) strength++;
    if (/[0-9]/.test(password)) strength++;
    if (/[^A-Za-z0-9]/.test(password)) strength++;
    
    strengthMeter.className = 'password-strength-meter';
    strengthMeter.style.transition = 'width 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
    
    if (password.length === 0) {
        strengthMeter.style.width = '0';
    } else if (strength <= 1) {
        strengthMeter.classList.add('weak');
        strengthMeter.style.width = '33%';
    } else if (strength <= 2) {
        strengthMeter.classList.add('medium');
        strengthMeter.style.width = '66%';
    } else {
        strengthMeter.classList.add('strong');
        strengthMeter.style.width = '100%';
    }
}

// ==================== MOBILE EVENT HANDLERS ====================

function setupMobileEvents() {
    // Mobile menu toggle
    const menuToggle = document.getElementById('menuToggle');
    const sidebar = document.getElementById('sidebar');
    
    if (menuToggle && sidebar) {
        menuToggle.addEventListener('click', () => {
            sidebar.classList.toggle('active');
            pulseAnimation(menuToggle);
            
            // Add backdrop when sidebar is open on mobile
            if (isMobile && sidebar.classList.contains('active')) {
                const backdrop = document.createElement('div');
                backdrop.className = 'sidebar-backdrop';
                backdrop.style.cssText = `
                    position: fixed;
                    top: 0;
                    left: 0;
                    right: 0;
                    bottom: 0;
                    background: rgba(0, 0, 0, 0.5);
                    z-index: var(--z-modal-backdrop);
                    backdrop-filter: blur(4px);
                `;
                document.body.appendChild(backdrop);
                
                backdrop.addEventListener('click', () => {
                    sidebar.classList.remove('active');
                    backdrop.remove();
                });
            }
        });
    }
    
    // Mobile search toggle
    const mobileSearchBtn = document.getElementById('mobileSearchBtn');
    const searchContainer = document.querySelector('.search-container');
    
    if (mobileSearchBtn && searchContainer) {
        mobileSearchBtn.addEventListener('click', () => {
            searchContainer.classList.toggle('active');
            if (searchContainer.classList.contains('active')) {
                const searchInput = document.getElementById('searchInput');
                if (searchInput) {
                    searchInput.focus();
                    // Show keyboard on mobile
                    searchInput.setAttribute('inputmode', 'search');
                }
            }
        });
    }
    
    // Mobile compose button
    const mobileComposeBtn = document.getElementById('mobileComposeBtn');
    const mobileComposeModal = document.getElementById('mobileComposeModal');
    
    if (mobileComposeBtn && mobileComposeModal) {
        mobileComposeBtn.addEventListener('click', () => {
            mobileComposeModal.classList.remove('hidden');
            document.getElementById('mobileTo')?.focus();
        });
    }
    
    // Mobile navigation
    const mobileNavItems = document.querySelectorAll('.mobile-nav-item');
    mobileNavItems.forEach(item => {
        item.addEventListener('click', (e) => {
            e.preventDefault();
            const action = item.dataset.action;
            
            // Update active state
            mobileNavItems.forEach(i => i.classList.remove('active'));
            item.classList.add('active');
            
            handleMobileNavAction(action);
        });
    });
    
    // Mobile more menu
    const mobileMoreBtn = document.querySelector('[data-action="more"]');
    const mobileMoreModal = document.getElementById('mobileMoreModal');
    
    if (mobileMoreBtn && mobileMoreModal) {
        mobileMoreBtn.addEventListener('click', () => {
            mobileMoreModal.classList.remove('hidden');
        });
    }
    
    // Close mobile modals
    const closeMobileCompose = document.getElementById('closeMobileCompose');
    const closeMobileMore = document.getElementById('closeMobileMore');
    
    if (closeMobileCompose && mobileComposeModal) {
        closeMobileCompose.addEventListener('click', () => {
            mobileComposeModal.classList.add('hidden');
        });
    }
    
    if (closeMobileMore && mobileMoreModal) {
        closeMobileMore.addEventListener('click', () => {
            mobileMoreModal.classList.add('hidden');
        });
    }
    
    // Mobile menu items
    const mobileMenuItems = document.querySelectorAll('.mobile-menu-item');
    mobileMenuItems.forEach(item => {
        item.addEventListener('click', () => {
            const action = item.dataset.action;
            handleMobileMenuAction(action);
            mobileMoreModal.classList.add('hidden');
        });
    });
    
    // Back button in email viewer
    const backToListBtn = document.getElementById('backToList');
    if (backToListBtn) {
        backToListBtn.addEventListener('click', () => {
            const emailList = document.getElementById('emailsList');
            const emailViewer = document.getElementById('emailViewer');
            const mobileViewerActions = document.querySelector('.mobile-viewer-actions');
            
            if (emailList && emailViewer) {
                emailList.style.display = 'block';
                emailViewer.style.display = 'none';
                
                if (mobileViewerActions) {
                    mobileViewerActions.style.display = 'none';
                }
            }
        });
    }
    
    // Mobile viewer actions
    const mobileViewerBtns = document.querySelectorAll('.mobile-viewer-btn');
    mobileViewerBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            const action = btn.dataset.action;
            handleMobileViewerAction(action);
        });
    });
}

function handleMobileNavAction(action) {
    switch(action) {
        case 'inbox':
            // Switch to inbox view
            showToast('Showing inbox', 'info');
            break;
            
        case 'starred':
            // Switch to starred view
            showToast('Showing starred emails', 'info');
            break;
            
        case 'sent':
            // Switch to sent view
            showToast('Showing sent emails', 'info');
            break;
            
        case 'compose':
            // Open compose modal
            const mobileComposeModal = document.getElementById('mobileComposeModal');
            if (mobileComposeModal) {
                mobileComposeModal.classList.remove('hidden');
                document.getElementById('mobileTo')?.focus();
            }
            break;
            
        case 'more':
            // Already handled by event listener
            break;
    }
}

function handleMobileMenuAction(action) {
    switch(action) {
        case 'settings':
            const settingsModal = document.getElementById('settingsModal');
            if (settingsModal) {
                settingsModal.classList.remove('hidden');
            }
            break;
            
        case 'help':
            showToast('Help center opening...', 'info');
            break;
            
        case 'feedback':
            showToast('Opening feedback form...', 'info');
            break;
            
        case 'logout':
            showToast('Logging out...', 'info');
            setTimeout(() => {
                window.location.reload();
            }, 1000);
            break;
    }
}

function handleMobileViewerAction(action) {
    const lang = TRANSLATIONS[currentLanguage];
    
    switch(action) {
        case 'reply':
            showToast('Opening reply...', 'info');
            break;
            
        case 'forward':
            showToast('Opening forward...', 'info');
            break;
            
        case 'star':
            showToast('Email starred', 'success');
            vibrate([100]);
            break;
            
        case 'archive':
            showToast('Email archived', 'success');
            vibrate([100]);
            break;
            
        case 'delete':
            showToast('Email deleted', 'success');
            vibrate([100, 50, 100]);
            break;
    }
}

// ==================== MAIN APP FUNCTIONS ====================

function showMainApp(user) {
    const loginScreen = document.getElementById('loginScreen');
    const app = document.getElementById('app');
    
    // Animate login screen out
    if (loginScreen) {
        loginScreen.style.opacity = '0';
        loginScreen.style.transform = 'translateY(-20px)';
        loginScreen.style.transition = 'all 0.5s cubic-bezier(0.4, 0, 0.2, 1)';
        
        setTimeout(() => {
            loginScreen.style.display = 'none';
        }, 500);
    }
    
    // Animate app in
    if (app) {
        app.style.display = 'flex';
        app.style.opacity = '0';
        app.style.transform = 'translateY(20px)';
        
        setTimeout(() => {
            app.style.opacity = '1';
            app.style.transform = 'translateY(0)';
            app.style.transition = 'all 0.5s cubic-bezier(0.4, 0, 0.2, 1)';
        }, 100);
    }
    
    // Update user info with animation
    updateUserInfo(user);
    
    // Setup mobile events
    if (isMobile) {
        setupMobileEvents();
        setupSwipeGestures();
    }
    
    // Setup quick actions
    setTimeout(setupQuickActions, 500);
}

function updateUserInfo(user) {
    const userNameElement = document.getElementById('userName');
    const userEmailElement = document.getElementById('userEmail');
    const userAvatarElement = document.getElementById('userAvatar');
    
    if (userNameElement) {
        userNameElement.textContent = user.displayName || 'User';
        slideIn(userNameElement, 'right');
    }
    
    if (userEmailElement) {
        userEmailElement.textContent = user.email || '';
        slideIn(userEmailElement, 'right');
    }
    
    if (userAvatarElement) {
        const initials = getInitialsFromName(user.displayName || user.email || 'User');
        userAvatarElement.textContent = initials;
        pulseAnimation(userAvatarElement);
    }
}

function getInitialsFromName(name) {
    const parts = name.split(' ');
    if (parts.length >= 2) {
        return (parts[0].charAt(0) + parts[1].charAt(0)).toUpperCase();
    }
    return name.substring(0, 2).toUpperCase();
}

// ==================== COMPOSE & AI FUNCTIONS ====================

function setupCompose() {
    const composeBtn = document.getElementById('composeBtn');
    const aiComposeBtn = document.getElementById('aiComposeBtn');
    const composeModal = document.getElementById('composeModal');
    const aiComposeModal = document.getElementById('aiComposeModal');
    const closeCompose = document.getElementById('closeCompose');
    const closeAICompose = document.getElementById('closeAICompose');
    const sendMailBtn = document.getElementById('sendMail');
    const saveDraftBtn = document.getElementById('saveDraftBtn');
    const aiGenerateBtn = document.getElementById('aiGenerateBtn');
    const useAIGeneratedBtn = document.getElementById('useAIGeneratedBtn');
    
    // Regular compose
    if (composeBtn && composeModal) {
        composeBtn.addEventListener('click', () => {
            composeModal.classList.remove('hidden');
            document.getElementById('mailTo')?.focus();
            slideIn(composeModal, 'up');
        });
    }
    
    // AI compose
    if (aiComposeBtn && aiComposeModal) {
        aiComposeBtn.addEventListener('click', () => {
            aiComposeModal.classList.remove('hidden');
            document.getElementById('aiPrompt')?.focus();
            slideIn(aiComposeModal, 'up');
        });
    }
    
    // Close buttons
    if (closeCompose && composeModal) {
        closeCompose.addEventListener('click', () => {
            composeModal.style.animation = 'slideOutDown 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
            setTimeout(() => {
                composeModal.classList.add('hidden');
                composeModal.style.animation = '';
                clearComposeForm();
            }, 300);
        });
    }
    
    if (closeAICompose && aiComposeModal) {
        closeAICompose.addEventListener('click', () => {
            aiComposeModal.style.animation = 'slideOutDown 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
            setTimeout(() => {
                aiComposeModal.classList.add('hidden');
                aiComposeModal.style.animation = '';
            }, 300);
        });
    }
    
    // Send email
    if (sendMailBtn) {
        sendMailBtn.addEventListener('click', async () => {
            const to = document.getElementById('mailTo')?.value.trim() || '';
            const subject = document.getElementById('mailSubject')?.value.trim() || '';
            const text = document.getElementById('mailText')?.value.trim() || '';
            
            if (!to || !subject || !text) {
                showToast('Please fill in all fields', 'error');
                return;
            }
            
            // Button animation
            sendMailBtn.disabled = true;
            sendMailBtn.innerHTML = '<span>Sending...</span>';
            sendMailBtn.style.transform = 'scale(0.98)';
            
            // Simulate sending
            await new Promise(resolve => setTimeout(resolve, 1500));
            
            const lang = TRANSLATIONS[currentLanguage];
            showToast(lang.emailSent, 'success');
            
            // Vibrate on mobile
            if (isMobile) {
                vibrate([100, 50, 100]);
            }
            
            // Reset button
            setTimeout(() => {
                sendMailBtn.disabled = false;
                sendMailBtn.innerHTML = `<span>✈️ ${lang.send}</span>`;
                sendMailBtn.style.transform = 'scale(1)';
                
                composeModal.style.animation = 'slideOutDown 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
                setTimeout(() => {
                    composeModal.classList.add('hidden');
                    composeModal.style.animation = '';
                    clearComposeForm();
                }, 300);
            }, 500);
        });
    }
    
    // Save draft
    if (saveDraftBtn) {
        saveDraftBtn.addEventListener('click', () => {
            const lang = TRANSLATIONS[currentLanguage];
            showToast(lang.emailSaved, 'success');
            
            composeModal.style.animation = 'slideOutDown 0.3s cubic-bezier(0.4, 0, 0.2, 1)';
            setTimeout(() => {
                composeModal.classList.add('hidden');
                composeModal.style.animation = '';
                clearComposeForm();
            }, 300);
        });
    }
    
    // AI Generate
    if (aiGenerateBtn) {
        aiGenerateBtn.addEventListener('click', async () => {
            const prompt = document.getElementById('aiPrompt')?.value.trim() || '';
            
            if (!prompt) {
                showToast('Please describe what you want to write', 'error');
                return;
            }
            
            // Show loading state
            aiGenerateBtn.disabled = true;
            aiGenerateBtn.innerHTML = '<span>🤖 Generating...</span>';
            
            const lang = TRANSLATIONS[currentLanguage];
            const aiWriting = document.querySelector('.ai-writing');
            if (aiWriting) {
                aiWriting.textContent = lang.aiWriting;
                aiWriting.style.display = 'block';
            }
            
            // Generate AI email
            const generatedEmail = await generateAIEmail(prompt);
            
            // Update preview
            document.getElementById('aiSubjectPreview').textContent = generatedEmail.subject;
            document.getElementById('aiBodyPreview').textContent = generatedEmail.body;
            
            // Show result container
            const aiResultContainer = document.getElementById('aiResultContainer');
            if (aiResultContainer) {
                aiResultContainer.style.display = 'block';
            }
            
            // Show success
            aiGenerateBtn.disabled = false;
            aiGenerateBtn.innerHTML = `<span>✨ ${lang.aiGenerateBtn}</span>`;
            
            if (aiWriting) {
                aiWriting.style.display = 'none';
            }
            
            showToast(lang.aiGenerated, 'success');
        });
    }
    
    // Use AI Generated
    if (useAIGeneratedBtn) {
        useAIGeneratedBtn.addEventListener('click', () => {
            const subject = document.getElementById('aiSubjectPreview')?.textContent || '';
            const body = document.getElementById('aiBodyPreview')?.textContent || '';
            
            if (!subject || !body) {
                showToast('Please generate an email first', 'error');
                return;
            }
            
            // Copy to compose form
            document.getElementById('mailSubject').value = subject;
            document.getElementById('mailText').value = body;
            
            // Switch to compose modal
            aiComposeModal.classList.add('hidden');
            composeModal.classList.remove('hidden');
            document.getElementById('mailTo')?.focus();
            
            showToast('AI email loaded into composer', 'success');
        });
    }
    
    // AI examples
    const aiExamples = document.querySelectorAll('.ai-example');
    aiExamples.forEach(example => {
        example.addEventListener('click', () => {
            const type = example.dataset.example;
            const examples = {
                meeting: "Write a professional email to schedule a meeting next week about the project timeline and deliverables.",
                followup: "Write a friendly follow-up email checking on the status of a proposal sent last week.",
                thankyou: "Write a thank you email to a colleague who helped with an important project.",
                introduction: "Write an introduction email to a new client introducing myself and my company's services."
            };
            
            if (examples[type]) {
                document.getElementById('aiPrompt').value = examples[type];
                document.getElementById('aiPrompt').focus();
            }
        });
    });
}

function clearComposeForm() {
    document.getElementById('mailTo').value = '';
    document.getElementById('mailSubject').value = '';
    document.getElementById('mailText').value = '';
    document.getElementById('urgentCheck').checked = false;
}

// ==================== SETTINGS FUNCTIONS ====================

function setupSettings() {
    const settingsBtn = document.getElementById('settingsBtn');
    const closeSettingsBtn = document.getElementById('closeSettings');
    const settingsModal = document.getElementById('settingsModal');
    const saveSettingsBtn = document.getElementById('saveSettings');
    const themeBtns = document.querySelectorAll('.theme-btn');
    
    // Open settings
    if (settingsBtn && settingsModal) {
        settingsBtn.addEventListener('click', () => {
            settingsModal.classList.remove('hidden');
            loadUserSettings();
        });
    }
    
    // Close settings
    if (closeSettingsBtn && settingsModal) {
        closeSettingsBtn.addEventListener('click', () => {
            settingsModal.classList.add('hidden');
        });
    }
    
    // Theme selection in settings
    themeBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            const theme = btn.dataset.theme;
            setTheme(theme);
        });
    });
    
    // Save settings
    if (saveSettingsBtn) {
        saveSettingsBtn.addEventListener('click', () => {
            saveUserSettings();
            settingsModal.classList.add('hidden');
            showToast('Settings saved successfully', 'success');
        });
    }
    
    // Settings tabs
    const tabBtns = document.querySelectorAll('.tab-btn');
    tabBtns.forEach(btn => {
        btn.addEventListener('click', () => {
            const tab = btn.dataset.tab;
            
            // Update active tab
            tabBtns.forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            
            // Show corresponding content
            document.querySelectorAll('.tab-content').forEach(content => {
                content.classList.remove('active');
            });
            document.getElementById(tab + 'Tab')?.classList.add('active');
        });
    });
}

function loadUserSettings() {
    // Load theme
    const savedTheme = localStorage.getItem('inboxpro-theme') || 'dark';
    
    // Load language
    const savedLang = localStorage.getItem('inboxpro-language') || 'en';
    document.getElementById('settingsLanguage').value = savedLang;
    
    // Load notification settings
    const notificationsEnabled = localStorage.getItem('notificationsEnabled') !== 'false';
    document.getElementById('notificationsEnabled').checked = notificationsEnabled;
    
    // Load mobile settings
    if (isMobile) {
        const touchGestures = localStorage.getItem('touchGestures') !== 'false';
        const mobileOptimization = localStorage.getItem('mobileOptimization') !== 'false';
        const dataSaver = localStorage.getItem('dataSaver') === 'true';
        const offlineMode = localStorage.getItem('offlineMode') === 'true';
        
        document.getElementById('touchGestures').checked = touchGestures;
        document.getElementById('mobileOptimization').checked = mobileOptimization;
        document.getElementById('dataSaver').checked = dataSaver;
        document.getElementById('offlineMode').checked = offlineMode;
    }
}

function saveUserSettings() {
    // Save language
    const language = document.getElementById('settingsLanguage').value;
    localStorage.setItem('inboxpro-language', language);
    setLanguage(language);
    
    // Save notification settings
    const notificationsEnabled = document.getElementById('notificationsEnabled').checked;
    localStorage.setItem('notificationsEnabled', notificationsEnabled);
    
    // Save mobile settings
    if (isMobile) {
        const touchGestures = document.getElementById('touchGestures').checked;
        const mobileOptimization = document.getElementById('mobileOptimization').checked;
        const dataSaver = document.getElementById('dataSaver').checked;
        const offlineMode = document.getElementById('offlineMode').checked;
        
        localStorage.setItem('touchGestures', touchGestures);
        localStorage.setItem('mobileOptimization', mobileOptimization);
        localStorage.setItem('dataSaver', dataSaver);
        localStorage.setItem('offlineMode', offlineMode);
    }
}

// ==================== INITIALIZATION ====================

function initApp() {
    console.log('✅ Initializing Inbox Pro with mobile support...');
    
    // Check device type
    checkMobile();
    
    // Load saved preferences
    const savedLang = localStorage.getItem('inboxpro-language') || 'en';
    const savedTheme = localStorage.getItem('inboxpro-theme') || 'dark';
    
    // Apply with delay for visual effect
    setTimeout(() => {
        setLanguage(savedLang);
        setTheme(savedTheme);
    }, 500);
    
    // Setup event listeners
    setupAuthForms();
    setupCompose();
    setupSettings();
    setupPWA();
    
    // Setup theme toggle
    const themeToggle = document.getElementById('themeToggle');
    const themeOptions = document.getElementById('themeOptions');
    
    if (themeToggle && themeOptions) {
        themeToggle.addEventListener('click', () => {
            themeOptions.classList.toggle('show');
            pulseAnimation(themeToggle);
        });
        
        // Close theme options when clicking outside
        document.addEventListener('click', (e) => {
            if (!themeToggle.contains(e.target) && !themeOptions.contains(e.target)) {
                themeOptions.classList.remove('show');
            }
        });
    }
    
    // Setup language selector
    document.querySelectorAll('#languageSelect, #appLanguageSelect').forEach(select => {
        select?.addEventListener('change', (e) => {
            setLanguage(e.target.value);
            pulseAnimation(e.target);
        });
    });
    
    // Setup mock auth
    mockAuth.onAuthStateChanged((user) => {
        if (user) {
            console.log('User logged in:', user.email);
            setTimeout(() => showMainApp(user), 1000);
        }
    });
    
    // Handle window resize
    window.addEventListener('resize', checkMobile);
    
    // Handle orientation change
    window.addEventListener('orientationchange', () => {
        setTimeout(checkMobile, 100);
    });
    
    // Hide loading screen after animations
    setTimeout(() => {
        hideLoadingScreen();
        console.log('✅ Inbox Pro ready with mobile support!');
    }, 2000);
}

// Start the app
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initApp);
} else {
    initApp();
}

// Export for debugging
window.InboxPro = {
    setLanguage,
    setTheme,
    generateAIEmail,
    showToast,
    checkMobile,
    isMobile: () => isMobile
};
