// Inbox Pro - Simple Working Version
console.log('🚀 Inbox Pro starting...');

// Basic translations
const TRANSLATIONS = {
    en: {
        // Loading
        loading: "Loading Inbox Pro...",
        
        // Login Screen
        welcomeBack: "Welcome Back",
        createAccount: "Create Account",
        resetPassword: "Reset Password",
        emailAddress: "Email Address",
        password: "Password",
        fullName: "Full Name",
        confirmPassword: "Confirm Password",
        rememberMe: "Remember me",
        forgotPassword: "Forgot password?",
        signIn: "Sign In",
        newUser: "New user?",
        haveAccount: "Already have an account?",
        rememberPassword: "Remember password?",
        sendResetLink: "Send Reset Link",
        createAccountBtn: "Create Account",
        passwordHint: "Minimum 8 characters with letters & numbers",
        
        // Features
        aiSpamFilter: "AI Spam Filter",
        smartSorting: "Smart Sorting",
        securePrivate: "Secure & Private",
        
        // Main App
        aiActive: "AI Active",
        aiOrganizing: "AI is organizing your inbox. <strong>15</strong> emails sorted automatically.",
        searchPlaceholder: "Search emails, contacts, subjects...",
        compose: "Compose",
        aiCompose: "AI Compose",
        archive: "Archive",
        important: "Important",
        delete: "Delete",
        snooze: "Snooze",
        folders: "FOLDERS",
        inbox: "Inbox",
        starred: "Starred",
        sent: "Sent",
        drafts: "Drafts",
        spam: "Spam",
        trash: "Trash",
        labels: "LABELS",
        work: "Work",
        personal: "Personal",
        travel: "Travel",
        social: "Social",
        emailStats: "Email Stats",
        total: "Total",
        unread: "Unread",
        storage: "Storage",
        used: "used",
        
        // Toolbar
        newestFirst: "Newest first",
        oldestFirst: "Oldest first",
        importantFirst: "Important first",
        unreadFirst: "Unread first",
        selectAll: "Select All",
        markRead: "Mark as Read",
        withAttachments: "With Attachments",
        all: "All",
        
        // Email Viewer
        reply: "Reply",
        forward: "Forward",
        print: "Print",
        back: "Back",
        
        // Compose Modal
        newMessage: "New Message",
        to: "To",
        subject: "Subject",
        writeMessage: "Write your message here...",
        send: "Send",
        saveDraft: "Save Draft",
        importantEmail: "Important",
        aiGenerate: "AI Generate",
        aiWriting: "AI is writing your email...",
        aiPrompt: "Describe what you want to write about:",
        aiGenerateBtn: "Generate Email",
        
        // Settings
        settings: "Settings",
        profile: "Profile",
        appearance: "Appearance",
        notifications: "Notifications",
        language: "Language",
        enableNotifications: "Enable notifications",
        interfaceLanguage: "Interface Language",
        saveChanges: "Save Changes",
        
        // Mobile
        mobileCompose: "Compose",
        mobileSearch: "Search",
        mobileInbox: "Inbox",
        mobileStarred: "Starred",
        mobileSent: "Sent",
        mobileMore: "More",
        
        // Toast Messages
        loginSuccess: "Login successful! Welcome to Inbox Pro.",
        registerSuccess: "Account created successfully!",
        emailSent: "Email sent successfully!",
        emailSaved: "Draft saved successfully!",
        aiGenerated: "Email generated by AI!",
        themeChanged: "Theme changed to",
        languageChanged: "Language changed to"
    },
    
    ua: {
        loading: "Завантаження Inbox Pro...",
        welcomeBack: "З поверненням",
        createAccount: "Створити акаунт",
        resetPassword: "Скинути пароль",
        emailAddress: "Електронна адреса",
        password: "Пароль",
        fullName: "Повне ім'я",
        confirmPassword: "Підтвердіть пароль",
        rememberMe: "Запам'ятати мене",
        forgotPassword: "Забули пароль?",
        signIn: "Увійти",
        newUser: "Новий користувач?",
        haveAccount: "Вже маєте акаунт?",
        rememberPassword: "Пам'ятаєте пароль?",
        sendResetLink: "Надіслати посилання",
        createAccountBtn: "Створити акаунт",
        passwordHint: "Мінімум 8 символів з літерами та цифрами",
        
        aiSpamFilter: "AI Фільтр Спаму",
        smartSorting: "Розумне Сортування",
        securePrivate: "Захищено & Приватно",
        
        aiActive: "AI Активний",
        aiOrganizing: "AI організовує вашу пошту. <strong>15</strong> листів відсортовано автоматично.",
        searchPlaceholder: "Пошук листів, контактів, тем...",
        compose: "Написати",
        aiCompose: "AI Написати",
        archive: "Архівувати",
        important: "Важливе",
        delete: "Видалити",
        snooze: "Відкласти",
        folders: "ПАПКИ",
        inbox: "Вхідні",
        starred: "Зірочка",
        sent: "Надіслані",
        drafts: "Чернетки",
        spam: "Спам",
        trash: "Кошик",
        labels: "МІТКИ",
        work: "Робота",
        personal: "Особисте",
        travel: "Подорожі",
        social: "Соціальне",
        emailStats: "Статистика",
        total: "Всього",
        unread: "Непрочитані",
        storage: "Сховище",
        used: "використано",
        
        newestFirst: "Спочатку нові",
        oldestFirst: "Спочатку старі",
        importantFirst: "Спочатку важливі",
        unreadFirst: "Спочатку непрочитані",
        selectAll: "Вибрати все",
        markRead: "Позначити прочитаним",
        withAttachments: "З файлами",
        all: "Всі",
        
        reply: "Відповісти",
        forward: "Переслати",
        print: "Друк",
        back: "Назад",
        
        newMessage: "Нове повідомлення",
        to: "Кому",
        subject: "Тема",
        writeMessage: "Напишіть ваше повідомлення тут...",
        send: "Надіслати",
        saveDraft: "Зберегти чернетку",
        importantEmail: "Важливо",
        aiGenerate: "AI Згенерувати",
        aiWriting: "AI пише ваш лист...",
        aiPrompt: "Опишіть, про що хочете написати:",
        aiGenerateBtn: "Згенерувати Лист",
        
        settings: "Налаштування",
        profile: "Профіль",
        appearance: "Зовнішній вигляд",
        notifications: "Сповіщення",
        language: "Мова",
        enableNotifications: "Увімкнути сповіщення",
        interfaceLanguage: "Мова інтерфейсу",
        saveChanges: "Зберегти зміни",
        
        mobileCompose: "Написати",
        mobileSearch: "Пошук",
        mobileInbox: "Вхідні",
        mobileStarred: "Зірочка",
        mobileSent: "Надіслані",
        mobileMore: "Більше",
        
        loginSuccess: "Вхід успішний! Ласкаво просимо до Inbox Pro.",
        registerSuccess: "Акаунт успішно створено!",
        emailSent: "Лист успішно відправлено!",
        emailSaved: "Чернетку успішно збережено!",
        aiGenerated: "Лист згенеровано AI!",
        themeChanged: "Тему змінено на",
        languageChanged: "Мову змінено на"
    }
};

// State
let currentLanguage = 'en';
let currentTheme = 'dark';
let currentUser = null;
let isMobile = false;

// ==================== CORE FUNCTIONS ====================

function hideLoadingScreen() {
    console.log('Hiding loading screen...');
    const loadingOverlay = document.getElementById('initialLoading');
    if (loadingOverlay) {
        loadingOverlay.style.opacity = '0';
        setTimeout(() => {
            loadingOverlay.style.display = 'none';
        }, 500);
    }
}

function showToast(message, type = 'info', duration = 5000) {
    const toastContainer = document.getElementById('toastContainer');
    if (!toastContainer) return;
    
    const toast = document.createElement('div');
    toast.className = `toast ${type}`;
    toast.style.animation = 'toastSlideIn 0.3s ease';
    
    const icons = {
        success: '✅',
        error: '❌',
        warning: '⚠️',
        info: 'ℹ️'
    };
    
    toast.innerHTML = `
        <span class="toast-icon">${icons[type] || 'ℹ️'}</span>
        <div class="toast-content">
            <div class="toast-message">${message}</div>
        </div>
        <button class="toast-close">✕</button>
    `;
    
    toastContainer.appendChild(toast);
    
    toast.querySelector('.toast-close').addEventListener('click', () => {
        toast.remove();
    });
    
    setTimeout(() => {
        if (toast.parentNode) {
            toast.remove();
        }
    }, duration);
}

// ==================== MOBILE FUNCTIONS ====================

function checkMobile() {
    isMobile = window.innerWidth <= 768;
    updateMobileUI();
}

function updateMobileUI() {
    const sidebar = document.getElementById('sidebar');
    const mobileNav = document.getElementById('mobileNav');
    const mobileHeaderActions = document.querySelector('.mobile-header-actions');
    const mobileActionsBar = document.querySelector('.mobile-actions-bar');
    
    if (isMobile) {
        if (sidebar) sidebar.classList.remove('active');
        if (mobileNav) mobileNav.style.display = 'flex';
        if (mobileHeaderActions) mobileHeaderActions.style.display = 'flex';
        if (mobileActionsBar) mobileActionsBar.style.display = 'flex';
        updateMobileLabels();
    } else {
        if (mobileNav) mobileNav.style.display = 'none';
        if (mobileHeaderActions) mobileHeaderActions.style.display = 'none';
        if (mobileActionsBar) mobileActionsBar.style.display = 'none';
    }
}

function updateMobileLabels() {
    const lang = TRANSLATIONS[currentLanguage];
    
    const mobileNavItems = document.querySelectorAll('.mobile-nav-item');
    mobileNavItems.forEach(item => {
        const action = item.dataset.action;
        const label = item.querySelector('.nav-label');
        
        if (label) {
            switch(action) {
                case 'inbox': label.textContent = lang.mobileInbox; break;
                case 'starred': label.textContent = lang.mobileStarred; break;
                case 'sent': label.textContent = lang.mobileSent; break;
                case 'more': label.textContent = lang.mobileMore; break;
            }
        }
    });
}

// ==================== THEME SYSTEM ====================

function setTheme(theme) {
    currentTheme = theme;
    localStorage.setItem('inboxpro-theme', theme);
    document.body.className = theme + '-theme';
    
    document.querySelectorAll('.theme-option, .theme-btn').forEach(btn => {
        btn.classList.remove('active');
        if (btn.dataset.theme === theme) {
            btn.classList.add('active');
        }
    });
    
    const themeIcon = document.querySelector('.theme-icon');
    if (themeIcon) {
        themeIcon.textContent = theme === 'light' ? '☀️' : theme === 'dark' ? '🌙' : '●';
    }
    
    const lang = TRANSLATIONS[currentLanguage];
    showToast(`${lang.themeChanged} ${theme}`, 'success');
}

// ==================== LANGUAGE SYSTEM ====================

function setLanguage(lang) {
    if (!TRANSLATIONS[lang]) lang = 'en';
    
    currentLanguage = lang;
    localStorage.setItem('inboxpro-language', lang);
    
    document.querySelectorAll('#languageSelect, #appLanguageSelect, #settingsLanguage').forEach(select => {
        if (select) select.value = lang;
    });
    
    updateTextElements();
    
    const langNames = { en: 'English', ua: 'Українська' };
    showToast(`${TRANSLATIONS[lang].languageChanged} ${langNames[lang]}`, 'success');
}

function updateTextElements() {
    const lang = TRANSLATIONS[currentLanguage];
    
    // Loading
    const loadingText = document.getElementById('loadingText');
    if (loadingText) loadingText.textContent = lang.loading;
    
    // Login Form
    const loginTitle = document.querySelector('#loginForm h2');
    if (loginTitle) loginTitle.innerHTML = `🔑 ${lang.welcomeBack}`;
    
    const registerTitle = document.querySelector('#registerForm h2');
    if (registerTitle) registerTitle.innerHTML = `👤 ${lang.createAccount}`;
    
    const resetTitle = document.querySelector('#resetForm h2');
    if (resetTitle) resetTitle.innerHTML = `🔑 ${lang.resetPassword}`;
    
    // Update labels
    const labels = {
        '#rememberMeText': lang.rememberMe,
        '#newUserText': lang.newUser,
        '#haveAccountText': lang.haveAccount,
        '#rememberPasswordText': lang.rememberPassword,
        '#loginBtn .btn-text': lang.signIn,
        '#registerBtn .btn-text': lang.createAccountBtn,
        '#sendResetBtn .btn-text': lang.sendResetLink,
        '.password-hint': lang.passwordHint,
        '.ai-text': lang.aiActive,
        '.compose-text': lang.compose,
        '.ai-compose-text': lang.aiCompose,
        '#searchInput': lang.searchPlaceholder
    };
    
    for (const selector in labels) {
        const element = document.querySelector(selector);
        if (element) {
            if (selector === '#searchInput') {
                element.placeholder = labels[selector];
            } else {
                element.textContent = labels[selector];
            }
        }
    }
    
    // Update features
    const features = document.querySelectorAll('.feature-text');
    if (features.length >= 3) {
        features[0].textContent = lang.aiSpamFilter;
        features[1].textContent = lang.smartSorting;
        features[2].textContent = lang.securePrivate;
    }
    
    // Update mobile labels
    if (isMobile) {
        updateMobileLabels();
    }
}

// ==================== AUTH FORMS ====================

function setupAuthForms() {
    // Form switching
    const showRegisterBtn = document.getElementById('showRegister');
    const showLoginBtn = document.getElementById('showLogin');
    const showLoginFromResetBtn = document.getElementById('showLoginFromReset');
    const forgotPasswordBtn = document.getElementById('forgotPasswordBtn');
    
    const loginForm = document.getElementById('loginForm');
    const registerForm = document.getElementById('registerForm');
    const resetForm = document.getElementById('resetForm');
    
    if (showRegisterBtn) {
        showRegisterBtn.addEventListener('click', (e) => {
            e.preventDefault();
            loginForm.classList.remove('active');
            registerForm.classList.add('active');
            resetForm.classList.remove('active');
        });
    }
    
    if (showLoginBtn) {
        showLoginBtn.addEventListener('click', (e) => {
            e.preventDefault();
            registerForm.classList.remove('active');
            loginForm.classList.add('active');
            resetForm.classList.remove('active');
        });
    }
    
    if (forgotPasswordBtn) {
        forgotPasswordBtn.addEventListener('click', (e) => {
            e.preventDefault();
            loginForm.classList.remove('active');
            registerForm.classList.remove('active');
            resetForm.classList.add('active');
        });
    }
    
    if (showLoginFromResetBtn) {
        showLoginFromResetBtn.addEventListener('click', (e) => {
            e.preventDefault();
            resetForm.classList.remove('active');
            loginForm.classList.add('active');
        });
    }
    
    // Login button
    const loginBtn = document.getElementById('loginBtn');
    if (loginBtn) {
        loginBtn.addEventListener('click', async () => {
            const email = document.getElementById('loginEmail').value;
            const password = document.getElementById('loginPassword').value;
            
            if (!email || !password) {
                showToast('Please fill in all fields', 'error');
                return;
            }
            
            loginBtn.disabled = true;
            loginBtn.innerHTML = '<span class="btn-text">Signing in...</span><span class="btn-icon">⏳</span>';
            
            // Simulate login
            await new Promise(resolve => setTimeout(resolve, 1000));
            
            const user = {
                uid: 'demo-user',
                email: email,
                displayName: email.split('@')[0]
            };
            
            showToast(TRANSLATIONS[currentLanguage].loginSuccess, 'success');
            showMainApp(user);
        });
    }
    
    // Register button
    const registerBtn = document.getElementById('registerBtn');
    if (registerBtn) {
        registerBtn.addEventListener('click', async () => {
            const name = document.getElementById('registerName').value;
            const email = document.getElementById('registerEmail').value;
            const password = document.getElementById('registerPassword').value;
            const confirm = document.getElementById('registerConfirm').value;
            
            if (!name || !email || !password || !confirm) {
                showToast('Please fill in all fields', 'error');
                return;
            }
            
            if (password !== confirm) {
                showToast('Passwords do not match', 'error');
                return;
            }
            
            if (password.length < 8) {
                showToast('Password must be at least 8 characters', 'error');
                return;
            }
            
            registerBtn.disabled = true;
            registerBtn.innerHTML = '<span class="btn-text">Creating...</span><span class="btn-icon">⏳</span>';
            
            // Simulate registration
            await new Promise(resolve => setTimeout(resolve, 1000));
            
            const user = {
                uid: 'demo-user',
                email: email,
                displayName: name
            };
            
            showToast(TRANSLATIONS[currentLanguage].registerSuccess, 'success');
            showMainApp(user);
        });
    }
    
    // Password strength indicator
    const passwordInput = document.getElementById('registerPassword');
    if (passwordInput) {
        passwordInput.addEventListener('input', updatePasswordStrength);
    }
}

function updatePasswordStrength() {
    const password = document.getElementById('registerPassword').value;
    const strengthMeter = document.querySelector('.password-strength-meter');
    if (!strengthMeter) return;
    
    let strength = 0;
    if (password.length >= 8) strength++;
    if (/[A-Z]/.test(password)) strength++;
    if (/[0-9]/.test(password)) strength++;
    if (/[^A-Za-z0-9]/.test(password)) strength++;
    
    strengthMeter.className = 'password-strength-meter';
    
    if (password.length === 0) {
        strengthMeter.style.width = '0';
    } else if (strength <= 1) {
        strengthMeter.classList.add('weak');
        strengthMeter.style.width = '33%';
    } else if (strength <= 2) {
        strengthMeter.classList.add('medium');
        strengthMeter.style.width = '66%';
    } else {
        strengthMeter.classList.add('strong');
        strengthMeter.style.width = '100%';
    }
}

// ==================== MAIN APP FUNCTIONS ====================

function showMainApp(user) {
    const loginScreen = document.getElementById('loginScreen');
    const app = document.getElementById('app');
    
    loginScreen.style.display = 'none';
    app.style.display = 'flex';
    
    // Update user info
    updateUserInfo(user);
    
    // Setup events
    setupAppEvents();
}

function updateUserInfo(user) {
    const userNameElement = document.getElementById('userName');
    const userEmailElement = document.getElementById('userEmail');
    const userAvatarElement = document.getElementById('userAvatar');
    
    if (userNameElement) userNameElement.textContent = user.displayName;
    if (userEmailElement) userEmailElement.textContent = user.email;
    if (userAvatarElement) {
        const initials = getInitialsFromName(user.displayName);
        userAvatarElement.textContent = initials;
    }
}

function getInitialsFromName(name) {
    const parts = name.split(' ');
    if (parts.length >= 2) {
        return (parts[0].charAt(0) + parts[1].charAt(0)).toUpperCase();
    }
    return name.substring(0, 2).toUpperCase();
}

// ==================== APP EVENTS ====================

function setupAppEvents() {
    // Menu toggle
    const menuToggle = document.getElementById('menuToggle');
    const sidebar = document.getElementById('sidebar');
    
    if (menuToggle && sidebar) {
        menuToggle.addEventListener('click', () => {
            sidebar.classList.toggle('active');
        });
    }
    
    // Theme toggle
    const themeToggle = document.getElementById('themeToggle');
    const themeOptions = document.getElementById('themeOptions');
    
    if (themeToggle && themeOptions) {
        themeToggle.addEventListener('click', () => {
            themeOptions.classList.toggle('show');
        });
        
        document.addEventListener('click', (e) => {
            if (!themeToggle.contains(e.target) && !themeOptions.contains(e.target)) {
                themeOptions.classList.remove('show');
            }
        });
    }
    
    // Theme selection
    document.querySelectorAll('.theme-option, .theme-btn').forEach(btn => {
        btn.addEventListener('click', () => {
            const theme = btn.dataset.theme;
            setTheme(theme);
            if (themeOptions) themeOptions.classList.remove('show');
        });
    });
    
    // Language selectors
    document.querySelectorAll('#languageSelect, #appLanguageSelect').forEach(select => {
        select.addEventListener('change', (e) => {
            setLanguage(e.target.value);
        });
    });
    
    // Compose
    const composeBtn = document.getElementById('composeBtn');
    const composeModal = document.getElementById('composeModal');
    const closeCompose = document.getElementById('closeCompose');
    const sendMailBtn = document.getElementById('sendMail');
    
    if (composeBtn && composeModal) {
        composeBtn.addEventListener('click', () => {
            composeModal.classList.remove('hidden');
        });
    }
    
    if (closeCompose && composeModal) {
        closeCompose.addEventListener('click', () => {
            composeModal.classList.add('hidden');
        });
    }
    
    if (sendMailBtn) {
        sendMailBtn.addEventListener('click', () => {
            const to = document.getElementById('mailTo').value;
            const subject = document.getElementById('mailSubject').value;
            
            if (!to || !subject) {
                showToast('Please fill in To and Subject', 'error');
                return;
            }
            
            showToast(TRANSLATIONS[currentLanguage].emailSent, 'success');
            composeModal.classList.add('hidden');
        });
    }
    
    // AI Compose
    const aiComposeBtn = document.getElementById('aiComposeBtn');
    const aiComposeModal = document.getElementById('aiComposeModal');
    const closeAICompose = document.getElementById('closeAICompose');
    const aiGenerateBtn = document.getElementById('aiGenerateBtn');
    
    if (aiComposeBtn && aiComposeModal) {
        aiComposeBtn.addEventListener('click', () => {
            aiComposeModal.classList.remove('hidden');
        });
    }
    
    if (closeAICompose && aiComposeModal) {
        closeAICompose.addEventListener('click', () => {
            aiComposeModal.classList.add('hidden');
        });
    }
    
    if (aiGenerateBtn) {
        aiGenerateBtn.addEventListener('click', async () => {
            const prompt = document.getElementById('aiPrompt').value;
            
            if (!prompt) {
                showToast('Please describe what you want to write', 'error');
                return;
            }
            
            aiGenerateBtn.disabled = true;
            aiGenerateBtn.innerHTML = '<span>🤖 Generating...</span>';
            
            const aiWriting = document.getElementById('aiWriting');
            if (aiWriting) aiWriting.style.display = 'block';
            
            // Simulate AI generation
            await new Promise(resolve => setTimeout(resolve, 1500));
            
            document.getElementById('aiSubjectPreview').textContent = 'AI Generated Email';
            document.getElementById('aiBodyPreview').textContent = 'This is a sample email generated by AI based on your request.';
            
            const aiResultContainer = document.getElementById('aiResultContainer');
            if (aiResultContainer) aiResultContainer.style.display = 'block';
            
            aiGenerateBtn.disabled = false;
            aiGenerateBtn.innerHTML = '<span>✨ Generate Email</span>';
            if (aiWriting) aiWriting.style.display = 'none';
            
            showToast(TRANSLATIONS[currentLanguage].aiGenerated, 'success');
        });
    }
    
    // Mobile events
    if (isMobile) {
        setupMobileAppEvents();
    }
    
    // Email actions
    setupEmailActions();
}

function setupMobileAppEvents() {
    // Mobile search
    const mobileSearchBtn = document.getElementById('mobileSearchBtn');
    const searchContainer = document.querySelector('.search-container');
    
    if (mobileSearchBtn && searchContainer) {
        mobileSearchBtn.addEventListener('click', () => {
            searchContainer.classList.toggle('active');
        });
    }
    
    // Mobile compose
    const mobileComposeBtn = document.getElementById('mobileComposeBtn');
    const mobileComposeModal = document.getElementById('mobileComposeModal');
    const closeMobileCompose = document.getElementById('closeMobileCompose');
    
    if (mobileComposeBtn && mobileComposeModal) {
        mobileComposeBtn.addEventListener('click', () => {
            mobileComposeModal.classList.remove('hidden');
        });
    }
    
    if (closeMobileCompose && mobileComposeModal) {
        closeMobileCompose.addEventListener('click', () => {
            mobileComposeModal.classList.add('hidden');
        });
    }
    
    // Mobile navigation
    const mobileNavItems = document.querySelectorAll('.mobile-nav-item');
    mobileNavItems.forEach(item => {
        item.addEventListener('click', (e) => {
            e.preventDefault();
            const action = item.dataset.action;
            
            mobileNavItems.forEach(i => i.classList.remove('active'));
            item.classList.add('active');
            
            handleMobileNavAction(action);
        });
    });
    
    // Mobile more menu
    const mobileMoreBtn = document.querySelector('[data-action="more"]');
    const mobileMoreModal = document.getElementById('mobileMoreModal');
    const closeMobileMore = document.getElementById('closeMobileMore');
    
    if (mobileMoreBtn && mobileMoreModal) {
        mobileMoreBtn.addEventListener('click', () => {
            mobileMoreModal.classList.remove('hidden');
        });
    }
    
    if (closeMobileMore && mobileMoreModal) {
        closeMobileMore.addEventListener('click', () => {
            mobileMoreModal.classList.add('hidden');
        });
    }
}

function handleMobileNavAction(action) {
    switch(action) {
        case 'inbox':
            showToast('Showing inbox', 'info');
            break;
        case 'starred':
            showToast('Showing starred emails', 'info');
            break;
        case 'sent':
            showToast('Showing sent emails', 'info');
            break;
        case 'compose':
            const mobileComposeModal = document.getElementById('mobileComposeModal');
            if (mobileComposeModal) {
                mobileComposeModal.classList.remove('hidden');
            }
            break;
        case 'more':
            const mobileMoreModal = document.getElementById('mobileMoreModal');
            if (mobileMoreModal) {
                mobileMoreModal.classList.remove('hidden');
            }
            break;
    }
}

function setupEmailActions() {
    // Email items
    const emailItems = document.querySelectorAll('.email-item');
    emailItems.forEach(item => {
        // Star button
        const starBtn = item.querySelector('.star-btn');
        if (starBtn) {
            starBtn.addEventListener('click', (e) => {
                e.stopPropagation();
                starBtn.classList.toggle('active');
                starBtn.textContent = starBtn.classList.contains('active') ? '★' : '☆';
                showToast('Email starred', 'success');
            });
        }
        
        // Archive button
        const archiveBtn = item.querySelector('.email-action:not(.star-btn)');
        if (archiveBtn) {
            archiveBtn.addEventListener('click', (e) => {
                e.stopPropagation();
                item.style.animation = 'slideOutLeft 0.3s ease';
                setTimeout(() => {
                    item.remove();
                    showToast('Email archived', 'success');
                }, 300);
            });
        }
        
        // Click to view
        item.addEventListener('click', (e) => {
            if (e.target.type !== 'checkbox' && !e.target.closest('.email-action')) {
                viewEmail(item);
            }
        });
    });
}

function viewEmail(emailItem) {
    const emailList = document.getElementById('emailsList');
    const emailViewer = document.getElementById('emailViewer');
    
    if (emailList && emailViewer) {
        emailList.style.display = 'none';
        emailViewer.style.display = 'flex';
        
        if (isMobile) {
            const mobileViewerActions = document.querySelector('.mobile-viewer-actions');
            if (mobileViewerActions) {
                mobileViewerActions.style.display = 'flex';
            }
        }
    }
}

// ==================== INITIALIZATION ====================

function initApp() {
    console.log('✅ Initializing Inbox Pro...');
    
    // Check device
    checkMobile();
    
    // Load saved settings
    const savedLang = localStorage.getItem('inboxpro-language') || 'en';
    const savedTheme = localStorage.getItem('inboxpro-theme') || 'dark';
    
    setLanguage(savedLang);
    setTheme(savedTheme);
    
    // Setup events
    setupAuthForms();
    
    // Handle window resize
    window.addEventListener('resize', checkMobile);
    
    // Hide loading screen after 1.5 seconds
    setTimeout(hideLoadingScreen, 1500);
    
    // Auto-login for testing (remove in production)
    // Для тестування можна автоматично увійти
    setTimeout(() => {
        if (document.getElementById('loginScreen').style.display !== 'none') {
            // Автоматично натискаємо кнопку входу для демо
            document.getElementById('loginBtn').click();
        }
    }, 2000);
}

// Start app when DOM is ready
if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initApp);
} else {
    initApp();
}

// Global error handler
window.addEventListener('error', function(e) {
    console.error('Global error:', e.message);
    // Force hide loading screen on error
    setTimeout(hideLoadingScreen, 100);
});
